export const COPY = {
  title: "Cockpit",
  lede: "Explore how open source moves",
  asOfPrefix: "as of",
  now: "Now",
  movingNow: "Moving now",
  speedingUp: "Speeding up",
  fasterThanLastMonth: "faster than last month",
  newOnTheMap: "New on the map",
  crossed10k: "10k",
  thisWeek: "This week",
  thisMonth: "This month",
  thisYear: "This year",
  vsLastMonth: "vs last month",
  faster: "faster",
  inCategory: "In AI / ML",
  was: "was",
  last90Days: "Last 90 days",
  nearby: "Nearby",
  compare: "Compare",
  fullHistory: "Full history",
  radar: "Open source this month",
  timeline: "Star history timeline",
  playhead: "Timeline playhead",
  search: "Find a repository",
  searchHint: "Search tracked repositories",
  empty: "—",
  climbing: "3rd month climbing",
  stars: "stars",
} as const;

export const FORBIDDEN_GLASS_TERMS = [
  "flow",
  "stock",
  "Momentum",
  "Acceleration",
  "intel",
  "p90",
  "7d",
  "30d",
  "ALL",
  "3M",
] as const;
