import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "Complete ranking",
  browseAllRepositories: "Browse all {count} repositories",
  page: "page",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "{year} GitHub Star Rankings - Yearly Movers",
  yearMetaDescription: "The {year} ranking of GitHub repositories by stars gained, with month-by-month history.",
  periodMetaTitle: "{label} GitHub Star Rankings",
  periodMetaDescription: "GitHub repositories ranked by stars gained in {label}.",
  categoryIndexMetaTitle: "GitHub Repository Categories",
  categoryIndexMetaDescription: "Browse tracked GitHub repositories by language, ecosystem, domain, project type, owner kind, and maturity.",
  categoryDimensionMetaTitle: "{label} Categories",
  categoryDimensionMetaDescription: "Browse tracked GitHub repositories by {label}.",
  categoryDetailMetaTitle: "{label} GitHub Repository Rankings{pageSuffix}",
  categoryDetailMetaDescription: "Tracked GitHub repositories in the {label} category by current stars{pageSuffix}.",
  pageSuffix: " - Page {page}",
  repositoryRankingsCaption: "{label} GitHub repository rankings",
  completeRepositoryRankingsCaption: "Complete {label} GitHub repository rankings",
  gainedCaption: "{label} GitHub repositories by stars gained",
  growthCaption: "{label} GitHub repositories by growth rate",
  crossedCaption: "{label} GitHub repositories crossing 10k stars",
  categorySummaryCaption: "Public GitHub repository categories",
  categoryDimensionSummaryCaption: "{label} GitHub repository categories",
  categoryDetailCaption: "{label} repositories by current stars",
  categoryPagination: "{label} pagination",
  range: "{first}-{last} of {total}",
  rankingDatasetName: "GitStarClub {label} Rankings Dataset",
  rankingDatasetDescription:
    "{label} GitHub repository rankings generated from GitStarClub's precomputed ranking data where available.",
  rankingCollectionName: "{label} GitHub repository rankings",
  rankingItemListName: "{label} GitHub repository rankings",
  rankingMetricGained: "stars gained in the selected period",
  rankingMetricTotal: "current total stars",
  rankingLeader: "{repo} leads with {value}",
  rankingFollowers: ", followed by {second} and {third}",
  rankingEmpty: "the visible list is waiting for rank rows",
  rankingCapsule:
    "As of {asOf}, {title} ranks tracked GitHub repositories by {metric}. {leader}{followers}. GitStarClub generates this visible ranking from GitStarClub's precomputed ranking and repository data, without runtime search, a database, or AI.",
  rankingWhatQ: "What does {title} rank?",
  rankingWhatAWithAsOf: "As of {asOf}, {title} ranks tracked GitHub repositories by {metric}.",
  rankingWhatANoAsOf: "{title} ranks tracked GitHub repositories by {metric} from GitStarClub's precomputed ranking data.",
  rankingLeaderQ: "Which repository leads {title}?",
  rankingLeaderA: "{repo} leads {title} with {value}.",
  rankingLeaderFallbackA: "The visible {title} list is waiting for rank rows.",
  rankingRunnerQ: "Who follows {repo} in {title}?",
  rankingRunnerFallbackQ: "Does {title} include runner-up repositories?",
  rankingRunnerA: "{repo} appears next in the visible ranking with {value}.",
  rankingRunnerFallbackA: "Runner-up rows appear when the precomputed ranking has at least two repositories.",
  rankingDataQ: "Does {title} use live database queries?",
  rankingDataA: "No. GitStarClub renders {title} from GitStarClub's precomputed ranking and repository data.",
  categoryIndexDatasetName: "GitStarClub Category Registry Dataset",
  categoryIndexDatasetDescription:
    "Browse public GitHub repository categories across language, ecosystem, domain, project type, owner kind, maturity, and more.",
  categoryIndexCollectionName: "GitHub repository categories",
  categoryIndexItemListName: "GitHub repository categories",
  categoryIndexCapsule:
    "As of {asOf}, browse {categories} public GitHub categories across {dimensions} dimensions, including {labels}. GitStarClub builds these category links from deterministic rules over repository metadata, not live search or AI, so readers can reach focused repository lists through crawlable pages.",
  categoryIndexQ: "What are GitHub repository categories on GitStarClub?",
  categoryIndexAWithAsOf: "As of {asOf}, GitStarClub organizes tracked repositories into {categories} public categories across {dimensions} dimensions.",
  categoryIndexANoAsOf: "GitStarClub organizes tracked repositories into {categories} public categories across {dimensions} dimensions using deterministic category data.",
  categoryDimensionsQ: "Which category dimensions are available?",
  categoryDimensionsA: "The visible category dimensions are {labels}.",
  categoryCountsQ: "Where do category counts come from?",
  categoryCountsA: "Category counts come from GitStarClub's own category data: deterministic rules over repository metadata, not live search or AI.",
  categoryMoveQ: "How can readers move from categories to repositories?",
  categoryMoveAWithDimension: "Readers can open a dimension such as {label}, then follow a category link to a ranked repository list.",
  categoryMoveAFallback: "Readers can open any visible dimension, then follow a category link to a ranked repository list.",
  categoryDimensionDatasetName: "GitStarClub {label} Category Dataset",
  categoryDimensionDatasetDescription:
    "Browse {label} category definitions, counts, and crawlable links for tracked GitHub repositories.",
  categoryDimensionCollectionName: "{label} categories",
  categoryDimensionItemListName: "{label} categories",
  categoryDimensionCapsule:
    "As of {asOf}, GitStarClub lists {categories} public categories in the {label} dimension for tracked GitHub repositories. This page uses deterministic rules over repository metadata, not live search or AI, with crawlable links that move readers and answer engines from broad taxonomy to specific repository rankings.",
  categoryDimensionQ: "What does the {label} category page include?",
  categoryDimensionAWithAsOf: "As of {asOf}, the {label} page lists {categories} public categories for tracked GitHub repositories.",
  categoryDimensionANoAsOf: "The {label} page lists {categories} public categories for tracked GitHub repositories using deterministic category data.",
  categoryLargestQ: "Which {label} category has the most tracked repositories?",
  categoryLargestA: "{category} is the largest visible {label} category with {count} tracked repositories.",
  categoryLargestFallbackA: "No public {label} category counts are available yet.",
  categoryLinksQ: "How are {label} category links generated?",
  categoryLinksA: "GitStarClub renders {label} links from the category registry, using public flags, slugs, labels, and counts that were precomputed before the request.",
  categoryNoClientQ: "Does the {label} page run client-side filtering?",
  categoryNoClientA: "No. The {label} page is server-rendered and does not add client-side filtering logic for the visible FAQ or category links.",
  categoryDetailDatasetName: "GitStarClub {label} Repository Dataset",
  categoryDetailDatasetDescription:
    "{label} repository rankings generated from deterministic category assignments, all-time ranking data, and repository metadata.",
  categoryDetailCollectionName: "{label} repositories",
  categoryDetailItemListName: "{label} repositories",
  categoryDetailCapsule:
    "As of {asOf}, GitStarClub tracks {count} repositories in {label}. {leader}{followers}. This category ranking uses deterministic category assignments, all-time ranking data, and repository metadata.",
  categoryDetailQ: "What repositories are included in {label}?",
  categoryDetailAWithAsOf:
    "As of {asOf}, {label} includes {count} repositories from GitStarClub's ≥10k whitelist — a deterministic rule slice, not a complete GitHub catalog.",
  categoryDetailANoAsOf:
    "{label} includes {count} repositories from GitStarClub's ≥10k whitelist according to the loaded category registry — a rule slice, not a complete GitHub catalog.",
  categoryDetailLeaderQ: "Which repository leads {label}?",
  categoryDetailLeaderA: "{repo} leads {label} with {value}.",
  categoryDetailLeaderFallbackA: "The {label} ranking is waiting for category rank rows.",
  categoryDetailRunnerQ: "Which repository follows {repo} in {label}?",
  categoryDetailRunnerFallbackQ: "Does {label} show runner-up repositories?",
  categoryDetailRunnerA: "{repo} follows in {label} with {value}.",
  categoryDetailRunnerFallbackA: "Runner-up repositories appear when category ranking rows are available.",
  categoryDetailDataQ: "How is the {label} ranking generated?",
  categoryDetailDataA:
    "GitStarClub combines deterministic category assignments, all-time ranking data, and repository metadata over the ≥10k whitelist. The page is not a complete GitHub language or topic listing, and it does not call live search or AI.",
  totalStarsValue: "{value} total stars",
  gainedStarsValue: "{value} stars",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "weekly movers are waiting for rank rows",
  pulseMonthFallback: "monthly movers are waiting for activity data",
  pulseWeekLead: "{repo} leads {period} with {value} stars gained",
  pulseMonthLead: "{repo} leads {period} with {value} stars gained",
  pulseCapsule:
    "As of {asOf}, GitStarClub Pulse summarizes current open-source momentum across tracked repositories. {weekLead}; {monthLead}. The page is generated from GitStarClub's precomputed activity and ranking data, not runtime search, a database, or AI.",
  pulseShowQ: "What does GitStarClub Pulse show?",
  pulseShowAWithAsOf: "As of {asOf}, GitStarClub Pulse summarizes current open-source momentum across tracked repositories.",
  pulseShowANoAsOf: "GitStarClub Pulse summarizes current open-source momentum from GitStarClub's precomputed activity and ranking data.",
  pulseWeekQ: "Which repository leads the latest available week {period}?",
  pulseWeekA: "{repo} leads {period} with {value} stars gained.",
  pulseWeekFallbackA: "The {period} weekly mover list is waiting for rank rows.",
  pulseMonthQ: "Which repository leads the current month view {period}?",
  pulseMonthA: "{repo} leads {period} with {value} stars gained.",
  pulseMonthFallbackA: "The {period} monthly mover list is waiting for activity data.",
  pulseDataQ: "What data powers Pulse?",
  pulseDataA: "Pulse uses GitStarClub's precomputed activity, weekly ranking, all-time ranking, and repository data.",
  rankingsRepoFallback: "the repository list is waiting for rows",
  rankingsOrgFallback: "the organization list is waiting for rows",
  rankingsRepoLead: "{repo} leads repositories with {value} total stars",
  rankingsOrgLead: "{org} leads organizations with {value} total stars across {repos} tracked repositories",
  rankingsCapsule:
    "As of {asOf}, GitStarClub's all-time rankings summarize the largest tracked GitHub repositories and organizations. {repoLead}, while {orgLead}. The page is built from GitStarClub's precomputed all-time ranking, repository, and organization data.",
  rankingsShowQ: "What do the all-time GitHub star rankings show?",
  rankingsShowAWithAsOf: "As of {asOf}, the all-time rankings list the largest tracked GitHub repositories and organizations by current total stars.",
  rankingsShowANoAsOf: "The all-time rankings list the largest tracked GitHub repositories and organizations by current total stars from GitStarClub's precomputed ranking data.",
  rankingsRepoQ: "Which repository leads the all-time ranking?",
  rankingsRepoA: "{repo} leads the visible repository ranking with {value} total stars.",
  rankingsRepoFallbackA: "The visible repository ranking is waiting for precomputed rank rows.",
  rankingsOrgQ: "Which organization leads the all-time ranking?",
  rankingsOrgA: "{org} leads the visible organization ranking with {value} total stars across {repos} tracked repositories.",
  rankingsOrgFallbackA: "The visible organization ranking is waiting for precomputed organization rank rows.",
  rankingsDataQ: "What data powers the all-time ranking FAQ?",
  rankingsDataA: "GitStarClub builds this FAQ from GitStarClub's precomputed all-time ranking, repository, and organization data.",
  compareCapsule:
    "As of {asOf}, GitStarClub Compare lets readers overlay tracked repository star-history curves from GitStarClub's precomputed star-history data. The static page explains absolute calendar history and 10k-aligned comparison without claiming client-only query-state facts as server-rendered evidence.",
  compareWhatQ: "What does GitStarClub Compare do?",
  compareWhatAWithAsOf: "As of {asOf}, GitStarClub Compare lets readers overlay tracked repository star-history curves from GitStarClub's precomputed star-history data.",
  compareWhatANoAsOf: "GitStarClub Compare lets readers overlay tracked repository star-history curves from GitStarClub's precomputed star-history data.",
  compareReposQ: "Which repositories can be compared?",
  compareReposA: "Compare accepts repositories already tracked by GitStarClub, using repository full names such as react/react and vuejs/vue.",
  compareModesQ: "What comparison modes are available?",
  compareModesA: "Readers can compare absolute calendar history or align repositories from their 10k-star milestone when that milestone is available.",
  compareQueryQ: "Does the compare FAQ describe URL query state?",
  compareQueryA: "No. The static compare page explains the deterministic comparison tool without claiming client-only query selections as server-rendered evidence.",
};
