import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "Ranking completo",
  browseAllRepositories: "Ver los {count} repositorios",
  page: "página",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "Ranking de estrellas GitHub {year} - crecimiento anual",
  yearMetaDescription: "Ranking {year} de repositorios GitHub por estrellas ganadas, con historia mes a mes.",
  periodMetaTitle: "Ranking de estrellas GitHub {label}",
  periodMetaDescription: "Repositorios GitHub ordenados por estrellas ganadas en {label}.",
  categoryIndexMetaTitle: "Categorías de repositorios GitHub",
  categoryIndexMetaDescription: "Explora repositorios GitHub monitoreados por lenguaje, ecosistema, dominio, tipo de proyecto, tipo de dueño y madurez.",
  categoryDimensionMetaTitle: "Categorías {label}",
  categoryDimensionMetaDescription: "Explora repositorios GitHub monitoreados por {label}.",
  categoryDetailMetaTitle: "Ranking de repositorios GitHub {label}{pageSuffix}",
  categoryDetailMetaDescription: "Repositorios GitHub monitoreados en la categoría {label}, ordenados por estrellas actuales{pageSuffix}.",
  pageSuffix: " - página {page}",
  repositoryRankingsCaption: "Ranking de repositorios GitHub {label}",
  completeRepositoryRankingsCaption: "Ranking completo de repositorios GitHub {label}",
  gainedCaption: "Repositorios GitHub {label} por estrellas ganadas",
  growthCaption: "Repositorios GitHub {label} por tasa de crecimiento",
  crossedCaption: "Repositorios GitHub que cruzaron 10k estrellas en {label}",
  categorySummaryCaption: "Categorías públicas de repositorios GitHub",
  categoryDimensionSummaryCaption: "Categorías de repositorios GitHub {label}",
  categoryDetailCaption: "Repositorios {label} por estrellas actuales",
  categoryPagination: "Paginación de {label}",
  range: "{first}-{last} de {total}",
  rankingDatasetName: "Dataset de rankings GitStarClub {label}",
  rankingDatasetDescription: "Rankings de repositorios GitHub {label} generados desde datos de ranking precalculados de GitStarClub cuando están disponibles.",
  rankingCollectionName: "Rankings de repositorios GitHub {label}",
  rankingItemListName: "Rankings de repositorios GitHub {label}",
  rankingMetricGained: "estrellas ganadas en el periodo seleccionado",
  rankingMetricTotal: "estrellas totales actuales",
  rankingLeader: "{repo} lidera con {value}",
  rankingFollowers: ", seguido por {second} y {third}",
  rankingEmpty: "la lista visible espera filas de ranking",
  rankingCapsule:
    "Al {asOf}, {title} ordena repositorios GitHub monitoreados por {metric}. {leader}{followers}. GitStarClub genera este ranking visible desde datos precalculados de ranking y repositorios, sin búsqueda, base de datos ni IA en tiempo de ejecución.",
  rankingWhatQ: "¿Qué ordena {title}?",
  rankingWhatAWithAsOf: "Al {asOf}, {title} ordena repositorios GitHub monitoreados por {metric}.",
  rankingWhatANoAsOf: "GitStarClub ordena en {title} repositorios GitHub monitoreados por {metric} desde datos de ranking precalculados.",
  rankingLeaderQ: "¿Qué repositorio lidera {title}?",
  rankingLeaderA: "{repo} lidera {title} con {value}.",
  rankingLeaderFallbackA: "La lista visible de {title} espera filas de ranking.",
  rankingRunnerQ: "¿Quién sigue a {repo} en {title}?",
  rankingRunnerFallbackQ: "¿{title} incluye repositorios de seguimiento?",
  rankingRunnerA: "{repo} aparece después en el ranking visible con {value}.",
  rankingRunnerFallbackA: "Las filas siguientes aparecen cuando el ranking precalculado tiene al menos dos repositorios.",
  rankingDataQ: "¿{title} usa consultas de base de datos en vivo?",
  rankingDataA: "No. GitStarClub renderiza {title} desde datos precalculados de ranking y repositorios.",
  categoryIndexDatasetName: "Dataset de registro de categorías GitStarClub",
  categoryIndexDatasetDescription: "Explore categorías públicas de repositorios GitHub por lenguaje, ecosistema, dominio, tipo de proyecto, tipo de propietario, madurez y más.",
  categoryIndexCollectionName: "Categorías de repositorios GitHub",
  categoryIndexItemListName: "Categorías de repositorios GitHub",
  categoryIndexCapsule:
    "Al {asOf}, GitStarClub organiza repositorios GitHub monitoreados en {categories} categorías públicas dentro de {dimensions} dimensiones, incluidas {labels}. Los enlaces de categoría se generan con reglas deterministas sobre metadatos de repositorios, no con búsqueda en vivo ni IA.",
  categoryIndexQ: "¿Qué son las categorías de repositorios GitHub en GitStarClub?",
  categoryIndexAWithAsOf: "Al {asOf}, GitStarClub organiza repositorios monitoreados en {categories} categorías públicas dentro de {dimensions} dimensiones.",
  categoryIndexANoAsOf: "GitStarClub organiza repositorios monitoreados en {categories} categorías públicas dentro de {dimensions} dimensiones.",
  categoryDimensionsQ: "¿Qué dimensiones de categoría están disponibles?",
  categoryDimensionsA: "Las dimensiones visibles son {labels}.",
  categoryCountsQ: "¿De dónde vienen los conteos de categoría?",
  categoryCountsA: "Los conteos vienen de los datos de categorías propios de GitStarClub: reglas deterministas sobre metadatos de repositorios, no búsqueda en vivo ni IA.",
  categoryMoveQ: "¿Cómo pasan los lectores de categorías a repositorios?",
  categoryMoveAWithDimension: "Los lectores pueden abrir una dimensión como {label} y seguir un enlace de categoría a una lista de repositorios rankeados.",
  categoryMoveAFallback: "Los lectores pueden abrir cualquier dimensión visible y seguir un enlace de categoría a una lista de repositorios rankeados.",
  categoryDimensionDatasetName: "Dataset de categorías GitStarClub {label}",
  categoryDimensionDatasetDescription: "Explore definiciones, conteos y enlaces rastreables de {label} para repositorios GitHub monitoreados.",
  categoryDimensionCollectionName: "Categorías {label}",
  categoryDimensionItemListName: "Categorías {label}",
  categoryDimensionCapsule:
    "Al {asOf}, GitStarClub lista {categories} categorías públicas en la dimensión {label} para repositorios GitHub monitoreados. Esta página usa reglas deterministas sobre metadatos de repositorios, no búsqueda en vivo ni IA, con enlaces rastreables que llevan de la taxonomía a rankings específicos.",
  categoryDimensionQ: "¿Qué incluye la página de categoría {label}?",
  categoryDimensionAWithAsOf: "Al {asOf}, la página {label} lista {categories} categorías públicas para repositorios GitHub monitoreados.",
  categoryDimensionANoAsOf: "La página {label} lista {categories} categorías públicas para repositorios GitHub monitoreados.",
  categoryLargestQ: "¿Qué categoría {label} tiene más repositorios monitoreados?",
  categoryLargestA: "{category} es la mayor categoría visible de {label} con {count} repositorios monitoreados.",
  categoryLargestFallbackA: "Aún no hay conteos públicos de categoría {label}.",
  categoryLinksQ: "¿Cómo se generan los enlaces de categoría {label}?",
  categoryLinksA: "GitStarClub renderiza enlaces {label} desde el registro de categorías, usando flags públicos, slugs, etiquetas y conteos precalculados antes de la solicitud.",
  categoryNoClientQ: "¿La página {label} ejecuta filtrado del lado del cliente?",
  categoryNoClientA: "No. La página {label} se renderiza en servidor y no agrega filtrado cliente para la FAQ visible ni enlaces de categoría.",
  categoryDetailDatasetName: "Dataset de repositorios GitStarClub {label}",
  categoryDetailDatasetDescription: "Rankings de repositorios {label} generados desde asignaciones deterministas de categoría, datos de ranking histórico y campos de repositorio.",
  categoryDetailCollectionName: "Repositorios {label}",
  categoryDetailItemListName: "Repositorios {label}",
  categoryDetailCapsule:
    "Al {asOf}, GitStarClub monitorea {count} repositorios en {label}. {leader}{followers}. Este ranking de categoría usa asignaciones deterministas de categoría, datos de ranking histórico y campos de repositorio.",
  categoryDetailQ: "¿Qué repositorios se incluyen en {label}?",
  categoryDetailAWithAsOf:
    "Al {asOf}, {label} incluye {count} repositorios de la lista blanca ≥10k de GitStarClub: un corte de reglas, no un catálogo completo de GitHub.",
  categoryDetailANoAsOf:
    "{label} incluye {count} repositorios de la lista blanca ≥10k según el registro cargado: un corte de reglas, no un catálogo completo de GitHub.",
  categoryDetailLeaderQ: "¿Qué repositorio lidera {label}?",
  categoryDetailLeaderA: "{repo} lidera {label} con {value}.",
  categoryDetailLeaderFallbackA: "El ranking {label} espera filas de ranking de categoría.",
  categoryDetailRunnerQ: "¿Qué repositorio sigue a {repo} en {label}?",
  categoryDetailRunnerFallbackQ: "¿{label} muestra repositorios de seguimiento?",
  categoryDetailRunnerA: "{repo} sigue en {label} con {value}.",
  categoryDetailRunnerFallbackA: "Los repositorios siguientes aparecen cuando hay filas de ranking de categoría disponibles.",
  categoryDetailDataQ: "¿Cómo se genera el ranking {label}?",
  categoryDetailDataA:
    "GitStarClub combina asignaciones deterministas de categoría, ranking histórico y campos de repositorio sobre la lista blanca ≥10k. No es un listado completo de GitHub ni llama búsqueda en vivo o IA.",
  totalStarsValue: "{value} estrellas totales",
  gainedStarsValue: "{value} estrellas",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "la lista semanal espera filas de ranking",
  pulseMonthFallback: "la lista mensual espera datos de actividad",
  pulseWeekLead: "{repo} lidera {period} con {value} estrellas ganadas",
  pulseMonthLead: "{repo} lidera {period} con {value} estrellas ganadas",
  pulseCapsule:
    "Al {asOf}, GitStarClub Pulse resume el impulso actual del código abierto en repositorios monitoreados. {weekLead}; {monthLead}. La página se genera desde datos precalculados de actividad y ranking de GitStarClub, no desde búsqueda, base de datos ni IA en tiempo de ejecución.",
  pulseShowQ: "¿Qué muestra GitStarClub Pulse?",
  pulseShowAWithAsOf: "Al {asOf}, GitStarClub Pulse resume el impulso actual del código abierto en repositorios monitoreados.",
  pulseShowANoAsOf: "GitStarClub Pulse resume el impulso actual del código abierto desde datos precalculados de actividad y ranking de GitStarClub.",
  pulseWeekQ: "¿Qué repositorio lidera la última semana disponible {period}?",
  pulseWeekA: "{repo} lidera {period} con {value} estrellas ganadas.",
  pulseWeekFallbackA: "La lista semanal de {period} espera filas de ranking.",
  pulseMonthQ: "¿Qué repositorio lidera la vista mensual actual {period}?",
  pulseMonthA: "{repo} lidera {period} con {value} estrellas ganadas.",
  pulseMonthFallbackA: "La lista mensual de {period} espera datos de actividad.",
  pulseDataQ: "¿Qué datos alimentan Pulse?",
  pulseDataA: "Pulse usa datos precalculados de actividad, ranking semanal, ranking histórico y repositorios de GitStarClub.",
  rankingsRepoFallback: "la lista de repositorios espera filas",
  rankingsOrgFallback: "la lista de organizaciones espera filas",
  rankingsRepoLead: "{repo} lidera los repositorios con {value} estrellas totales",
  rankingsOrgLead: "{org} lidera las organizaciones con {value} estrellas totales en {repos} repositorios monitoreados",
  rankingsCapsule:
    "Al {asOf}, los rankings históricos de GitStarClub resumen los mayores repositorios y organizaciones de GitHub monitoreados. {repoLead}, mientras {orgLead}. La página se construye desde datos precalculados de ranking histórico, repositorios y organizaciones de GitStarClub.",
  rankingsShowQ: "¿Qué muestran los rankings históricos de estrellas de GitHub?",
  rankingsShowAWithAsOf: "Al {asOf}, los rankings históricos listan los mayores repositorios y organizaciones de GitHub monitoreados por estrellas totales actuales.",
  rankingsShowANoAsOf: "Los rankings históricos listan los mayores repositorios y organizaciones de GitHub monitoreados por estrellas totales actuales desde datos de ranking precalculados de GitStarClub.",
  rankingsRepoQ: "¿Qué repositorio lidera el ranking histórico?",
  rankingsRepoA: "{repo} lidera el ranking visible de repositorios con {value} estrellas totales.",
  rankingsRepoFallbackA: "El ranking visible de repositorios espera filas de ranking precalculadas.",
  rankingsOrgQ: "¿Qué organización lidera el ranking histórico?",
  rankingsOrgA: "{org} lidera el ranking visible de organizaciones con {value} estrellas totales en {repos} repositorios monitoreados.",
  rankingsOrgFallbackA: "El ranking visible de organizaciones espera filas de ranking precalculadas.",
  rankingsDataQ: "¿Qué datos alimentan la FAQ del ranking histórico?",
  rankingsDataA: "GitStarClub construye esta FAQ desde datos precalculados de ranking histórico, repositorios y organizaciones.",
  compareCapsule:
    "Al {asOf}, GitStarClub Compare permite superponer curvas de historial de estrellas desde datos de historial de estrellas precalculados de GitStarClub. La página estática explica historial calendario absoluto y comparación alineada a 10k sin presentar estado de consulta solo del cliente como evidencia renderizada en servidor.",
  compareWhatQ: "¿Qué hace GitStarClub Compare?",
  compareWhatAWithAsOf: "Al {asOf}, GitStarClub Compare permite superponer curvas de historial de estrellas desde datos de historial de estrellas precalculados de GitStarClub.",
  compareWhatANoAsOf: "GitStarClub Compare permite superponer curvas de historial de estrellas desde datos de historial de estrellas precalculados de GitStarClub.",
  compareReposQ: "¿Qué repositorios se pueden comparar?",
  compareReposA: "Compare acepta repositorios ya monitoreados por GitStarClub, usando nombres completos como react/react y vuejs/vue.",
  compareModesQ: "¿Qué modos de comparación hay?",
  compareModesA: "Los lectores pueden comparar historial calendario absoluto o alinear repositorios desde su hito de 10k estrellas cuando está disponible.",
  compareQueryQ: "¿La FAQ de compare describe el estado de query de la URL?",
  compareQueryA: "No. La página estática de compare explica la herramienta determinista sin presentar selecciones solo del cliente como evidencia renderizada en servidor.",
};
