import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "Classement complet",
  browseAllRepositories: "Voir les {count} dépôts",
  page: "page",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "Classement d'étoiles GitHub {year} - progression annuelle",
  yearMetaDescription: "Le classement {year} des dépôts GitHub par étoiles gagnées, avec un historique mois par mois.",
  periodMetaTitle: "Classement d'étoiles GitHub {label}",
  periodMetaDescription: "Dépôts GitHub classés par étoiles gagnées pendant {label}.",
  categoryIndexMetaTitle: "Catégories de dépôts GitHub",
  categoryIndexMetaDescription: "Parcourez les dépôts GitHub suivis par langage, écosystème, domaine, type de projet, type de propriétaire et maturité.",
  categoryDimensionMetaTitle: "Catégories {label}",
  categoryDimensionMetaDescription: "Parcourez les dépôts GitHub suivis par {label}.",
  categoryDetailMetaTitle: "Classement des dépôts GitHub {label}{pageSuffix}",
  categoryDetailMetaDescription: "Dépôts GitHub suivis dans la catégorie {label}, classés par étoiles actuelles{pageSuffix}.",
  pageSuffix: " - page {page}",
  repositoryRankingsCaption: "Classement des dépôts GitHub {label}",
  completeRepositoryRankingsCaption: "Classement complet des dépôts GitHub {label}",
  gainedCaption: "Dépôts GitHub {label} par étoiles gagnées",
  growthCaption: "Dépôts GitHub {label} par taux de croissance",
  crossedCaption: "Dépôts GitHub ayant franchi 10k étoiles pendant {label}",
  categorySummaryCaption: "Catégories publiques de dépôts GitHub",
  categoryDimensionSummaryCaption: "Catégories de dépôts GitHub {label}",
  categoryDetailCaption: "Dépôts {label} par étoiles actuelles",
  categoryPagination: "Pagination {label}",
  range: "{first}-{last} sur {total}",
  rankingDatasetName: "Jeu de données de classement GitStarClub {label}",
  rankingDatasetDescription: "Classements de dépôts GitHub {label} générés depuis les données de classement précalculées de GitStarClub lorsqu'elles sont disponibles.",
  rankingCollectionName: "Classements de dépôts GitHub {label}",
  rankingItemListName: "Classements de dépôts GitHub {label}",
  rankingMetricGained: "étoiles gagnées pendant la période sélectionnée",
  rankingMetricTotal: "étoiles totales actuelles",
  rankingLeader: "{repo} mène avec {value}",
  rankingFollowers: ", suivi de {second} et {third}",
  rankingEmpty: "la liste visible attend des lignes de classement",
  rankingCapsule:
    "Au {asOf}, {title} classe les dépôts GitHub suivis par {metric}. {leader}{followers}. GitStarClub génère ce classement visible depuis des données de classement et de dépôts précalculées, sans recherche, base de données ni IA à l'exécution.",
  rankingWhatQ: "Que classe {title} ?",
  rankingWhatAWithAsOf: "Au {asOf}, {title} classe les dépôts GitHub suivis par {metric}.",
  rankingWhatANoAsOf: "GitStarClub classe dans {title} les dépôts GitHub suivis par {metric} depuis des données de classement précalculées.",
  rankingLeaderQ: "Quel dépôt mène {title} ?",
  rankingLeaderA: "{repo} mène {title} avec {value}.",
  rankingLeaderFallbackA: "La liste visible de {title} attend des lignes de classement.",
  rankingRunnerQ: "Qui suit {repo} dans {title} ?",
  rankingRunnerFallbackQ: "{title} inclut-il des dépôts suivants ?",
  rankingRunnerA: "{repo} apparaît ensuite dans le classement visible avec {value}.",
  rankingRunnerFallbackA: "Les lignes suivantes apparaissent lorsque le classement précalculé contient au moins deux dépôts.",
  rankingDataQ: "{title} utilise-t-il des requêtes de base de données en direct ?",
  rankingDataA: "Non. GitStarClub rend {title} depuis des données de classement et de dépôts précalculées.",
  categoryIndexDatasetName: "Jeu de données du registre de catégories GitStarClub",
  categoryIndexDatasetDescription: "Parcourez les catégories publiques de dépôts GitHub par langage, écosystème, domaine, type de projet, type de propriétaire, maturité, et plus.",
  categoryIndexCollectionName: "Catégories de dépôts GitHub",
  categoryIndexItemListName: "Catégories de dépôts GitHub",
  categoryIndexCapsule:
    "Au {asOf}, GitStarClub organise les dépôts GitHub suivis en {categories} catégories publiques sur {dimensions} dimensions, dont {labels}. Les liens de catégorie viennent de règles déterministes sur les métadonnées de dépôts, pas d'une recherche en direct ni d'une IA.",
  categoryIndexQ: "Que sont les catégories de dépôts GitHub sur GitStarClub ?",
  categoryIndexAWithAsOf: "Au {asOf}, GitStarClub organise les dépôts suivis en {categories} catégories publiques sur {dimensions} dimensions.",
  categoryIndexANoAsOf: "GitStarClub organise les dépôts suivis en {categories} catégories publiques sur {dimensions} dimensions.",
  categoryDimensionsQ: "Quelles dimensions de catégorie sont disponibles ?",
  categoryDimensionsA: "Les dimensions visibles sont {labels}.",
  categoryCountsQ: "D'où viennent les comptes de catégories ?",
  categoryCountsA: "Les comptes viennent des données de catégories propres à GitStarClub : des règles déterministes sur les métadonnées de dépôts, pas d'une recherche en direct ni d'une IA.",
  categoryMoveQ: "Comment passer des catégories aux dépôts ?",
  categoryMoveAWithDimension: "Les lecteurs peuvent ouvrir une dimension comme {label}, puis suivre un lien de catégorie vers une liste de dépôts classés.",
  categoryMoveAFallback: "Les lecteurs peuvent ouvrir n'importe quelle dimension visible, puis suivre un lien de catégorie vers une liste de dépôts classés.",
  categoryDimensionDatasetName: "Jeu de données de catégories GitStarClub {label}",
  categoryDimensionDatasetDescription: "Parcourez les définitions, comptes et liens explorables {label} pour les dépôts GitHub suivis.",
  categoryDimensionCollectionName: "Catégories {label}",
  categoryDimensionItemListName: "Catégories {label}",
  categoryDimensionCapsule:
    "Au {asOf}, GitStarClub liste {categories} catégories publiques dans la dimension {label} pour les dépôts GitHub suivis. Cette page utilise des règles déterministes sur les métadonnées de dépôts, pas une recherche en direct ni une IA, avec des liens explorables vers des classements précis.",
  categoryDimensionQ: "Que contient la page de catégorie {label} ?",
  categoryDimensionAWithAsOf: "Au {asOf}, la page {label} liste {categories} catégories publiques pour les dépôts GitHub suivis.",
  categoryDimensionANoAsOf: "La page {label} liste {categories} catégories publiques pour les dépôts GitHub suivis.",
  categoryLargestQ: "Quelle catégorie {label} contient le plus de dépôts suivis ?",
  categoryLargestA: "{category} est la plus grande catégorie visible {label} avec {count} dépôts suivis.",
  categoryLargestFallbackA: "Aucun compte public de catégorie {label} n'est encore disponible.",
  categoryLinksQ: "Comment les liens de catégorie {label} sont-ils générés ?",
  categoryLinksA: "GitStarClub rend les liens {label} depuis le registre de catégories, avec les flags publics, slugs, labels et comptes précalculés avant la requête.",
  categoryNoClientQ: "La page {label} exécute-t-elle un filtrage côté client ?",
  categoryNoClientA: "Non. La page {label} est rendue côté serveur et n'ajoute pas de filtrage client pour la FAQ visible ou les liens de catégorie.",
  categoryDetailDatasetName: "Jeu de données de dépôts GitStarClub {label}",
  categoryDetailDatasetDescription: "Classements de dépôts {label} générés depuis des affectations de catégorie déterministes, des données de classement historique et des champs de dépôts.",
  categoryDetailCollectionName: "Dépôts {label}",
  categoryDetailItemListName: "Dépôts {label}",
  categoryDetailCapsule:
    "Au {asOf}, GitStarClub suit {count} dépôts dans {label}. {leader}{followers}. Ce classement de catégorie utilise des affectations de catégorie déterministes, des données de classement historique et des champs de dépôts.",
  categoryDetailQ: "Quels dépôts sont inclus dans {label} ?",
  categoryDetailAWithAsOf:
    "Au {asOf}, {label} inclut {count} dépôts de la liste blanche ≥10k de GitStarClub — une tranche de règles, pas un catalogue GitHub complet.",
  categoryDetailANoAsOf:
    "{label} inclut {count} dépôts de la liste blanche ≥10k selon le registre chargé — une tranche de règles, pas un catalogue GitHub complet.",
  categoryDetailLeaderQ: "Quel dépôt mène {label} ?",
  categoryDetailLeaderA: "{repo} mène {label} avec {value}.",
  categoryDetailLeaderFallbackA: "Le classement {label} attend des lignes de classement de catégorie.",
  categoryDetailRunnerQ: "Quel dépôt suit {repo} dans {label} ?",
  categoryDetailRunnerFallbackQ: "{label} affiche-t-il des dépôts suivants ?",
  categoryDetailRunnerA: "{repo} suit dans {label} avec {value}.",
  categoryDetailRunnerFallbackA: "Les dépôts suivants apparaissent lorsque des lignes de classement de catégorie sont disponibles.",
  categoryDetailDataQ: "Comment le classement {label} est-il généré ?",
  categoryDetailDataA:
    "GitStarClub combine des affectations déterministes, des classements historiques et des champs de dépôts sur la liste blanche ≥10k. Ce n'est pas un listing GitHub complet, et la page n'appelle ni recherche en direct ni IA.",
  totalStarsValue: "{value} étoiles totales",
  gainedStarsValue: "{value} étoiles",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "la liste hebdomadaire attend les lignes de classement",
  pulseMonthFallback: "la liste mensuelle attend les données d'activité",
  pulseWeekLead: "{repo} mène {period} avec {value} étoiles gagnées",
  pulseMonthLead: "{repo} mène {period} avec {value} étoiles gagnées",
  pulseCapsule:
    "Au {asOf}, GitStarClub Pulse résume la dynamique open source actuelle parmi les dépôts suivis. {weekLead}; {monthLead}. La page est générée depuis les données d'activité et de classement précalculées de GitStarClub, sans recherche, base de données ni IA à l'exécution.",
  pulseShowQ: "Que montre GitStarClub Pulse ?",
  pulseShowAWithAsOf: "Au {asOf}, GitStarClub Pulse résume la dynamique open source actuelle parmi les dépôts suivis.",
  pulseShowANoAsOf: "GitStarClub Pulse résume la dynamique open source actuelle depuis les données d'activité et de classement précalculées de GitStarClub.",
  pulseWeekQ: "Quel dépôt mène la dernière semaine disponible {period} ?",
  pulseWeekA: "{repo} mène {period} avec {value} étoiles gagnées.",
  pulseWeekFallbackA: "La liste hebdomadaire {period} attend les lignes de classement.",
  pulseMonthQ: "Quel dépôt mène la vue mensuelle actuelle {period} ?",
  pulseMonthA: "{repo} mène {period} avec {value} étoiles gagnées.",
  pulseMonthFallbackA: "La liste mensuelle {period} attend les données d'activité.",
  pulseDataQ: "Quelles données alimentent Pulse ?",
  pulseDataA: "Pulse utilise les données précalculées d'activité, de classement hebdomadaire, de classement historique et de dépôts de GitStarClub.",
  rankingsRepoFallback: "la liste des dépôts attend des lignes",
  rankingsOrgFallback: "la liste des organisations attend des lignes",
  rankingsRepoLead: "{repo} mène les dépôts avec {value} étoiles totales",
  rankingsOrgLead: "{org} mène les organisations avec {value} étoiles totales sur {repos} dépôts suivis",
  rankingsCapsule:
    "Au {asOf}, les classements historiques de GitStarClub résument les plus grands dépôts et organisations GitHub suivis. {repoLead}, tandis que {orgLead}. La page est construite depuis les données précalculées de classement historique, de dépôts et d'organisations de GitStarClub.",
  rankingsShowQ: "Que montrent les classements historiques d'étoiles GitHub ?",
  rankingsShowAWithAsOf: "Au {asOf}, les classements historiques listent les plus grands dépôts et organisations GitHub suivis par étoiles totales actuelles.",
  rankingsShowANoAsOf: "Les classements historiques listent les plus grands dépôts et organisations GitHub suivis par étoiles totales actuelles depuis les données de classement précalculées de GitStarClub.",
  rankingsRepoQ: "Quel dépôt mène le classement historique ?",
  rankingsRepoA: "{repo} mène le classement visible des dépôts avec {value} étoiles totales.",
  rankingsRepoFallbackA: "Le classement visible des dépôts attend des lignes de classement précalculées.",
  rankingsOrgQ: "Quelle organisation mène le classement historique ?",
  rankingsOrgA: "{org} mène le classement visible des organisations avec {value} étoiles totales sur {repos} dépôts suivis.",
  rankingsOrgFallbackA: "Le classement visible des organisations attend des lignes de classement précalculées.",
  rankingsDataQ: "Quelles données alimentent la FAQ du classement historique ?",
  rankingsDataA: "GitStarClub construit cette FAQ depuis les données précalculées de classement historique, de dépôts et d'organisations.",
  compareCapsule:
    "Au {asOf}, GitStarClub Compare permet de superposer les courbes d'historique des étoiles depuis les données d'historique des étoiles précalculées de GitStarClub. La page statique explique l'historique calendaire absolu et la comparaison alignée sur 10k sans présenter l'état de requête côté client comme preuve rendue côté serveur.",
  compareWhatQ: "Que fait GitStarClub Compare ?",
  compareWhatAWithAsOf: "Au {asOf}, GitStarClub Compare permet de superposer les courbes d'historique des étoiles depuis les données d'historique des étoiles précalculées de GitStarClub.",
  compareWhatANoAsOf: "GitStarClub Compare permet de superposer les courbes d'historique des étoiles depuis les données d'historique des étoiles précalculées de GitStarClub.",
  compareReposQ: "Quels dépôts peuvent être comparés ?",
  compareReposA: "Compare accepte les dépôts déjà suivis par GitStarClub, avec des noms complets comme react/react et vuejs/vue.",
  compareModesQ: "Quels modes de comparaison sont disponibles ?",
  compareModesA: "Les lecteurs peuvent comparer l'historique calendaire absolu ou aligner les dépôts depuis leur jalon de 10k étoiles lorsqu'il est disponible.",
  compareQueryQ: "La FAQ compare décrit-elle l'état de query de l'URL ?",
  compareQueryA: "Non. La page statique compare explique l'outil déterministe sans présenter les sélections côté client comme preuve rendue côté serveur.",
};
