import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "完全なランキング",
  browseAllRepositories: "{count} 件のリポジトリをすべて見る",
  page: "ページ",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "{year} GitHub スターランキング - 年間上昇",
  yearMetaDescription: "{year} 年にスターを増やした GitHub リポジトリのランキングと月別履歴。",
  periodMetaTitle: "{label} GitHub スターランキング",
  periodMetaDescription: "{label} に獲得したスター数で GitHub リポジトリを順位付けします。",
  categoryIndexMetaTitle: "GitHub リポジトリカテゴリ",
  categoryIndexMetaDescription: "追跡対象 GitHub リポジトリを言語、エコシステム、ドメイン、種類、所有者種別、成熟度で閲覧できます。",
  categoryDimensionMetaTitle: "{label} カテゴリ",
  categoryDimensionMetaDescription: "{label} で追跡対象 GitHub リポジトリを閲覧できます。",
  categoryDetailMetaTitle: "{label} GitHub リポジトリランキング{pageSuffix}",
  categoryDetailMetaDescription: "{label} カテゴリの追跡 GitHub リポジトリを現在スター数で表示します{pageSuffix}。",
  pageSuffix: " - {page} ページ",
  repositoryRankingsCaption: "{label} GitHub リポジトリランキング",
  completeRepositoryRankingsCaption: "{label} GitHub リポジトリランキング完全版",
  gainedCaption: "{label} GitHub リポジトリのスター増加順",
  growthCaption: "{label} GitHub リポジトリの成長率順",
  crossedCaption: "{label} で 1 万スターに到達した GitHub リポジトリ",
  categorySummaryCaption: "公開 GitHub リポジトリカテゴリ",
  categoryDimensionSummaryCaption: "{label} GitHub リポジトリカテゴリ",
  categoryDetailCaption: "{label} リポジトリの現在スター順",
  categoryPagination: "{label} ページ送り",
  range: "{total} 件中 {first}-{last}",
  rankingDatasetName: "GitStarClub {label} ランキングデータセット",
  rankingDatasetDescription: "利用可能な GitStarClub の事前計算ランキングデータから生成される {label} の GitHub リポジトリランキングです。",
  rankingCollectionName: "{label} GitHub リポジトリランキング",
  rankingItemListName: "{label} GitHub リポジトリランキング",
  rankingMetricGained: "選択期間に獲得したスター",
  rankingMetricTotal: "現在の総スター数",
  rankingLeader: "{repo} が {value} でリードしています",
  rankingFollowers: "、続いて {second} と {third}",
  rankingEmpty: "表示リストはランキング行を待っています",
  rankingCapsule:
    "{asOf} 時点で、{title} は追跡対象 GitHub リポジトリを{metric}で並べています。{leader}{followers}。GitStarClub は事前計算済みのランキングデータとリポジトリデータからこのランキングを生成し、実行時検索、データベース、AI は使いません。",
  rankingWhatQ: "{title} は何をランキングしていますか？",
  rankingWhatAWithAsOf: "{asOf} 時点で、{title} は追跡対象 GitHub リポジトリを{metric}で順位付けしています。",
  rankingWhatANoAsOf: "{title} は GitStarClub の事前計算ランキングデータから追跡対象 GitHub リポジトリを{metric}で順位付けします。",
  rankingLeaderQ: "{title} の首位リポジトリは？",
  rankingLeaderA: "{repo} が {title} を {value} でリードしています。",
  rankingLeaderFallbackA: "{title} の表示リストはランキング行を待っています。",
  rankingRunnerQ: "{title} で {repo} に続くリポジトリは？",
  rankingRunnerFallbackQ: "{title} には次点リポジトリがありますか？",
  rankingRunnerA: "{repo} が表示ランキングで次に並び、{value} です。",
  rankingRunnerFallbackA: "事前計算ランキングに 2 件以上のリポジトリがある場合、次点行が表示されます。",
  rankingDataQ: "{title} はライブデータベースクエリを使いますか？",
  rankingDataA: "いいえ。GitStarClub は事前計算済みのランキングデータとリポジトリデータから {title} をレンダリングします。",
  categoryIndexDatasetName: "GitStarClub カテゴリレジストリデータセット",
  categoryIndexDatasetDescription: "公開 GitHub リポジトリカテゴリを、言語、エコシステム、ドメイン、プロジェクト種別、所有者種別、成熟度などで閲覧できます。",
  categoryIndexCollectionName: "GitHub リポジトリカテゴリ",
  categoryIndexItemListName: "GitHub リポジトリカテゴリ",
  categoryIndexCapsule:
    "{asOf} 時点で、GitStarClub は追跡対象 GitHub リポジトリを {dimensions} 個の次元、{categories} 個の公開カテゴリに整理しています。例: {labels}。カテゴリリンクはリポジトリメタデータに対する決定的なルールから作られ、ライブ検索や AI ではありません。",
  categoryIndexQ: "GitStarClub の GitHub リポジトリカテゴリとは？",
  categoryIndexAWithAsOf: "{asOf} 時点で、GitStarClub は追跡リポジトリを {dimensions} 個の次元、{categories} 個の公開カテゴリに整理しています。",
  categoryIndexANoAsOf: "GitStarClub は追跡リポジトリを {dimensions} 個の次元、{categories} 個の公開カテゴリに整理します。",
  categoryDimensionsQ: "利用できるカテゴリ次元は？",
  categoryDimensionsA: "表示中のカテゴリ次元は {labels} です。",
  categoryCountsQ: "カテゴリ件数の出典は？",
  categoryCountsA: "カテゴリ件数は GitStarClub 独自のカテゴリデータに由来します。リポジトリメタデータに対する決定的なルールであり、ライブ検索や AI ではありません。",
  categoryMoveQ: "カテゴリからリポジトリへどう移動できますか？",
  categoryMoveAWithDimension: "{label} などの次元を開き、カテゴリリンクからランキング済みリポジトリ一覧へ移動できます。",
  categoryMoveAFallback: "表示されている任意の次元を開き、カテゴリリンクからランキング済みリポジトリ一覧へ移動できます。",
  categoryDimensionDatasetName: "GitStarClub {label} カテゴリデータセット",
  categoryDimensionDatasetDescription: "{label} のカテゴリ定義、件数、クロール可能なリンクを閲覧できます。",
  categoryDimensionCollectionName: "{label} カテゴリ",
  categoryDimensionItemListName: "{label} カテゴリ",
  categoryDimensionCapsule:
    "{asOf} 時点で、GitStarClub は追跡対象 GitHub リポジトリ向けに {label} 次元の公開カテゴリ {categories} 件を表示しています。このページはリポジトリメタデータに対する決定的なルールを使い、ライブ検索や AI ではなく、クロール可能なリンクでカテゴリからリポジトリランキングへ移動できます。",
  categoryDimensionQ: "{label} カテゴリページには何が含まれますか？",
  categoryDimensionAWithAsOf: "{asOf} 時点で、{label} ページは追跡 GitHub リポジトリ向けの公開カテゴリ {categories} 件を表示します。",
  categoryDimensionANoAsOf: "{label} ページは追跡 GitHub リポジトリ向けの公開カテゴリ {categories} 件を表示します。",
  categoryLargestQ: "{label} で最も追跡リポジトリが多いカテゴリは？",
  categoryLargestA: "{category} は表示中の {label} カテゴリで最大で、{count} 件の追跡リポジトリがあります。",
  categoryLargestFallbackA: "公開 {label} カテゴリ件数はまだ利用できません。",
  categoryLinksQ: "{label} カテゴリリンクはどう生成されますか？",
  categoryLinksA: "GitStarClub は事前計算された public フラグ、slug、label、count を使い、カテゴリレジストリから {label} リンクをレンダリングします。",
  categoryNoClientQ: "{label} ページはクライアント側フィルタを実行しますか？",
  categoryNoClientA: "いいえ。{label} ページはサーバーレンダリングされ、表示 FAQ やカテゴリリンクにクライアント側フィルタを追加しません。",
  categoryDetailDatasetName: "GitStarClub {label} リポジトリデータセット",
  categoryDetailDatasetDescription: "{label} リポジトリランキングは、決定的なカテゴリ割り当て、通算ランキングデータ、リポジトリ項目から生成されます。",
  categoryDetailCollectionName: "{label} リポジトリ",
  categoryDetailItemListName: "{label} リポジトリ",
  categoryDetailCapsule:
    "{asOf} 時点で、GitStarClub は {label} に {count} 件のリポジトリを追跡しています。{leader}{followers}。このカテゴリランキングは決定的なカテゴリ割り当て、通算ランキングデータ、リポジトリ項目から生成されます。",
  categoryDetailQ: "{label} にはどのリポジトリが含まれますか？",
  categoryDetailAWithAsOf:
    "{asOf} 時点で、{label} には GitStarClub の ≥10k ホワイトリストから {count} 件が含まれます。決定的なルール切片であり、GitHub の完全な一覧ではありません。",
  categoryDetailANoAsOf:
    "{label} には読み込まれたカテゴリレジストリにもとづき、≥10k ホワイトリストから {count} 件が含まれます。ルール切片であり、GitHub の完全な一覧ではありません。",
  categoryDetailLeaderQ: "{label} の首位リポジトリは？",
  categoryDetailLeaderA: "{repo} が {label} を {value} でリードしています。",
  categoryDetailLeaderFallbackA: "{label} ランキングはカテゴリランキング行を待っています。",
  categoryDetailRunnerQ: "{label} で {repo} に続くリポジトリは？",
  categoryDetailRunnerFallbackQ: "{label} は次点リポジトリを表示しますか？",
  categoryDetailRunnerA: "{repo} が {label} で続き、{value} です。",
  categoryDetailRunnerFallbackA: "カテゴリランキング行が利用できる場合、次点リポジトリが表示されます。",
  categoryDetailDataQ: "{label} ランキングはどう生成されますか？",
  categoryDetailDataA:
    "GitStarClub は ≥10k ホワイトリスト上の決定的なカテゴリ割り当て、通算ランキングデータ、リポジトリ項目を組み合わせます。GitHub の言語やトピックの完全な一覧ではなく、ライブ検索や AI も呼び出しません。",
  totalStarsValue: "{value} 総スター",
  gainedStarsValue: "{value} スター",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "週次の上昇リポジトリはランキング行を待っています",
  pulseMonthFallback: "月次の上昇リポジトリはアクティビティデータを待っています",
  pulseWeekLead: "{repo} が {period} を {value} スター獲得でリードしています",
  pulseMonthLead: "{repo} が {period} を {value} スター獲得でリードしています",
  pulseCapsule:
    "{asOf} 時点で、GitStarClub Pulse は追跡対象リポジトリの現在のオープンソース動向をまとめます。{weekLead}。{monthLead}。このページは GitStarClub の事前計算済みアクティビティデータとランキングデータから生成され、実行時検索、データベース、AI は使いません。",
  pulseShowQ: "GitStarClub Pulse は何を表示しますか？",
  pulseShowAWithAsOf: "{asOf} 時点で、GitStarClub Pulse は追跡対象リポジトリの現在のオープンソース動向をまとめます。",
  pulseShowANoAsOf: "GitStarClub Pulse は GitStarClub の事前計算済みアクティビティデータとランキングデータから現在のオープンソース動向をまとめます。",
  pulseWeekQ: "利用可能な最新週 {period} をリードするリポジトリは？",
  pulseWeekA: "{repo} が {period} を {value} スター獲得でリードしています。",
  pulseWeekFallbackA: "{period} の週次上昇リストはランキング行を待っています。",
  pulseMonthQ: "現在の月次ビュー {period} をリードするリポジトリは？",
  pulseMonthA: "{repo} が {period} を {value} スター獲得でリードしています。",
  pulseMonthFallbackA: "{period} の月次上昇リストはアクティビティデータを待っています。",
  pulseDataQ: "Pulse のデータソースは何ですか？",
  pulseDataA: "Pulse は GitStarClub の事前計算済みアクティビティデータ、週次ランキングデータ、通算ランキングデータ、リポジトリデータを使います。",
  rankingsRepoFallback: "リポジトリ一覧は行を待っています",
  rankingsOrgFallback: "組織一覧は行を待っています",
  rankingsRepoLead: "リポジトリでは {repo} が {value} 総スターでリードしています",
  rankingsOrgLead: "組織では {org} が {repos} 件の追跡リポジトリで {value} 総スターを持ちリードしています",
  rankingsCapsule:
    "{asOf} 時点で、GitStarClub の通算ランキングは最大規模の追跡 GitHub リポジトリと組織をまとめます。{repoLead}。一方、{orgLead}。このページは GitStarClub の事前計算済み通算ランキング、リポジトリ、組織データから作られます。",
  rankingsShowQ: "通算 GitHub スターランキングは何を示しますか？",
  rankingsShowAWithAsOf: "{asOf} 時点で、通算ランキングは現在の総スター数にもとづき最大規模の追跡 GitHub リポジトリと組織を表示します。",
  rankingsShowANoAsOf: "通算ランキングは GitStarClub の事前計算ランキングデータから、現在の総スター数にもとづく最大規模の追跡 GitHub リポジトリと組織を表示します。",
  rankingsRepoQ: "通算ランキングで首位のリポジトリは？",
  rankingsRepoA: "{repo} が可視リポジトリランキングを {value} 総スターでリードしています。",
  rankingsRepoFallbackA: "可視リポジトリランキングは事前計算済みランキング行を待っています。",
  rankingsOrgQ: "通算ランキングで首位の組織は？",
  rankingsOrgA: "{org} が {repos} 件の追跡リポジトリで {value} 総スターを持ち、可視組織ランキングをリードしています。",
  rankingsOrgFallbackA: "可視組織ランキングは事前計算済み組織ランキング行を待っています。",
  rankingsDataQ: "通算ランキング FAQ のデータソースは？",
  rankingsDataA: "GitStarClub は事前計算済み通算ランキング、リポジトリ、組織データからこの FAQ を作ります。",
  compareCapsule:
    "{asOf} 時点で、GitStarClub Compare は GitStarClub の事前計算済みスター履歴データから追跡リポジトリのスター履歴カーブを重ねられます。静的ページは絶対カレンダー履歴と 1 万到達基準の比較を説明し、クライアントだけのクエリ状態をサーバーレンダリングの根拠として扱いません。",
  compareWhatQ: "GitStarClub Compare は何をしますか？",
  compareWhatAWithAsOf: "{asOf} 時点で、GitStarClub Compare は GitStarClub の事前計算済みスター履歴データから追跡リポジトリのスター履歴カーブを重ねられます。",
  compareWhatANoAsOf: "GitStarClub Compare は GitStarClub の事前計算済みスター履歴データから追跡リポジトリのスター履歴カーブを重ねられます。",
  compareReposQ: "どのリポジトリを比較できますか？",
  compareReposA: "Compare は react/react や vuejs/vue のような full name を使い、GitStarClub に追跡済みのリポジトリを受け付けます。",
  compareModesQ: "利用できる比較モードは？",
  compareModesA: "読者は絶対カレンダー履歴、または利用可能な場合は 1 万スター到達から揃えた比較を選べます。",
  compareQueryQ: "compare FAQ は URL クエリ状態を説明しますか？",
  compareQueryA: "いいえ。静的 compare ページは決定的な比較ツールを説明し、クライアントだけの選択をサーバーレンダリング済みの根拠とは扱いません。",
};
