import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "전체 순위",
  browseAllRepositories: "저장소 {count}개 모두 보기",
  page: "페이지",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "{year} GitHub 스타 순위 - 연간 상승",
  yearMetaDescription: "{year}년에 스타를 얻은 GitHub 저장소 순위와 월별 히스토리입니다.",
  periodMetaTitle: "{label} GitHub 스타 순위",
  periodMetaDescription: "{label} 동안 얻은 스타 수로 GitHub 저장소를 정렬합니다.",
  categoryIndexMetaTitle: "GitHub 저장소 카테고리",
  categoryIndexMetaDescription: "언어, 생태계, 도메인, 프로젝트 유형, 소유자 유형, 성숙도로 추적 GitHub 저장소를 탐색합니다.",
  categoryDimensionMetaTitle: "{label} 카테고리",
  categoryDimensionMetaDescription: "{label} 기준으로 추적 GitHub 저장소를 탐색합니다.",
  categoryDetailMetaTitle: "{label} GitHub 저장소 순위{pageSuffix}",
  categoryDetailMetaDescription: "{label} 카테고리의 추적 GitHub 저장소를 현재 스타 순으로 보여줍니다{pageSuffix}.",
  pageSuffix: " - {page}페이지",
  repositoryRankingsCaption: "{label} GitHub 저장소 순위",
  completeRepositoryRankingsCaption: "{label} GitHub 저장소 전체 순위",
  gainedCaption: "{label} GitHub 저장소 스타 증가 순위",
  growthCaption: "{label} GitHub 저장소 성장률 순위",
  crossedCaption: "{label}에서 1만 스타를 넘은 GitHub 저장소",
  categorySummaryCaption: "공개 GitHub 저장소 카테고리",
  categoryDimensionSummaryCaption: "{label} GitHub 저장소 카테고리",
  categoryDetailCaption: "{label} 저장소 현재 스타 순위",
  categoryPagination: "{label} 페이지 이동",
  range: "총 {total}개 중 {first}-{last}",
  rankingDatasetName: "GitStarClub {label} 순위 데이터셋",
  rankingDatasetDescription: "{label} GitHub 저장소 순위는 사용 가능한 GitStarClub의 사전 계산 순위 데이터에서 생성됩니다.",
  rankingCollectionName: "{label} GitHub 저장소 순위",
  rankingItemListName: "{label} GitHub 저장소 순위",
  rankingMetricGained: "선택 기간에 얻은 스타",
  rankingMetricTotal: "현재 총 스타",
  rankingLeader: "{repo}가 {value}로 앞서고 있습니다",
  rankingFollowers: ", 이어서 {second} 및 {third}",
  rankingEmpty: "표시 목록은 순위 행을 기다리고 있습니다",
  rankingCapsule:
    "{asOf} 기준으로 {title}은 추적 GitHub 저장소를 {metric} 기준으로 정렬합니다. {leader}{followers}. GitStarClub은 런타임 검색, 데이터베이스, AI 없이 사전 계산 순위 및 저장소 데이터로 이 순위를 생성합니다.",
  rankingWhatQ: "{title}은 무엇을 순위화하나요?",
  rankingWhatAWithAsOf: "{asOf} 기준으로 {title}은 추적 GitHub 저장소를 {metric} 기준으로 순위화합니다.",
  rankingWhatANoAsOf: "{title}은 GitStarClub의 사전 계산 순위 데이터에서 추적 GitHub 저장소를 {metric} 기준으로 순위화합니다.",
  rankingLeaderQ: "{title}을 이끄는 저장소는 무엇인가요?",
  rankingLeaderA: "{repo}가 {value}로 {title}을 이끌고 있습니다.",
  rankingLeaderFallbackA: "{title} 표시 목록은 순위 행을 기다리고 있습니다.",
  rankingRunnerQ: "{title}에서 {repo} 다음은 무엇인가요?",
  rankingRunnerFallbackQ: "{title}에는 후속 저장소가 포함되나요?",
  rankingRunnerA: "{repo}가 {value}로 표시 순위 다음에 있습니다.",
  rankingRunnerFallbackA: "사전 계산 순위에 저장소가 두 개 이상 있으면 후속 행이 표시됩니다.",
  rankingDataQ: "{title}은 실시간 데이터베이스 쿼리를 사용하나요?",
  rankingDataA: "아니요. GitStarClub은 사전 계산 순위 및 저장소 데이터에서 {title}을 렌더링합니다.",
  categoryIndexDatasetName: "GitStarClub 카테고리 레지스트리 데이터셋",
  categoryIndexDatasetDescription: "언어, 생태계, 도메인, 프로젝트 유형, 소유자 유형, 성숙도 등으로 공개 GitHub 저장소 카테고리를 둘러보세요.",
  categoryIndexCollectionName: "GitHub 저장소 카테고리",
  categoryIndexItemListName: "GitHub 저장소 카테고리",
  categoryIndexCapsule:
    "{asOf} 기준으로 GitStarClub은 추적 GitHub 저장소를 {dimensions}개 차원, {categories}개 공개 카테고리로 정리합니다. 예: {labels}. 카테고리 링크는 저장소 메타데이터에 대한 결정적 규칙에서 생성되며 실시간 검색이나 AI가 아닙니다.",
  categoryIndexQ: "GitStarClub의 GitHub 저장소 카테고리는 무엇인가요?",
  categoryIndexAWithAsOf: "{asOf} 기준으로 GitStarClub은 추적 저장소를 {dimensions}개 차원, {categories}개 공개 카테고리로 정리합니다.",
  categoryIndexANoAsOf: "GitStarClub은 추적 저장소를 {dimensions}개 차원, {categories}개 공개 카테고리로 정리합니다.",
  categoryDimensionsQ: "사용 가능한 카테고리 차원은 무엇인가요?",
  categoryDimensionsA: "표시되는 카테고리 차원은 {labels}입니다.",
  categoryCountsQ: "카테고리 수는 어디서 오나요?",
  categoryCountsA: "카테고리 수는 GitStarClub의 자체 카테고리 데이터에서 옵니다. 저장소 메타데이터에 대한 결정적 규칙이며 실시간 검색이나 AI가 아닙니다.",
  categoryMoveQ: "카테고리에서 저장소로 어떻게 이동하나요?",
  categoryMoveAWithDimension: "{label} 같은 차원을 열고 카테고리 링크를 따라 순위화된 저장소 목록으로 이동할 수 있습니다.",
  categoryMoveAFallback: "표시된 차원을 열고 카테고리 링크를 따라 순위화된 저장소 목록으로 이동할 수 있습니다.",
  categoryDimensionDatasetName: "GitStarClub {label} 카테고리 데이터셋",
  categoryDimensionDatasetDescription: "추적 GitHub 저장소를 위한 {label} 카테고리 정의, 수, 크롤 가능한 링크를 둘러보세요.",
  categoryDimensionCollectionName: "{label} 카테고리",
  categoryDimensionItemListName: "{label} 카테고리",
  categoryDimensionCapsule:
    "{asOf} 기준으로 GitStarClub은 추적 GitHub 저장소의 {label} 차원에 공개 카테고리 {categories}개를 표시합니다. 이 페이지는 저장소 메타데이터에 대한 결정적 규칙을 사용하며 실시간 검색이나 AI가 아니고, 크롤 가능한 링크로 카테고리에서 저장소 순위로 이동할 수 있게 합니다.",
  categoryDimensionQ: "{label} 카테고리 페이지에는 무엇이 포함되나요?",
  categoryDimensionAWithAsOf: "{asOf} 기준으로 {label} 페이지는 추적 GitHub 저장소의 공개 카테고리 {categories}개를 표시합니다.",
  categoryDimensionANoAsOf: "{label} 페이지는 추적 GitHub 저장소의 공개 카테고리 {categories}개를 표시합니다.",
  categoryLargestQ: "어떤 {label} 카테고리에 추적 저장소가 가장 많나요?",
  categoryLargestA: "{category}는 표시된 {label} 카테고리 중 가장 크며 추적 저장소 {count}개가 있습니다.",
  categoryLargestFallbackA: "공개 {label} 카테고리 수는 아직 사용할 수 없습니다.",
  categoryLinksQ: "{label} 카테고리 링크는 어떻게 생성되나요?",
  categoryLinksA: "GitStarClub은 요청 전에 사전 계산된 public 플래그, slug, label, count를 사용해 카테고리 레지스트리에서 {label} 링크를 렌더링합니다.",
  categoryNoClientQ: "{label} 페이지는 클라이언트 필터링을 실행하나요?",
  categoryNoClientA: "아니요. {label} 페이지는 서버 렌더링되며 표시 FAQ나 카테고리 링크에 클라이언트 필터링을 추가하지 않습니다.",
  categoryDetailDatasetName: "GitStarClub {label} 저장소 데이터셋",
  categoryDetailDatasetDescription: "{label} 저장소 순위는 결정적 카테고리 할당, 역대 순위 데이터, 저장소 필드에서 생성됩니다.",
  categoryDetailCollectionName: "{label} 저장소",
  categoryDetailItemListName: "{label} 저장소",
  categoryDetailCapsule:
    "{asOf} 기준으로 GitStarClub은 {label}에서 저장소 {count}개를 추적합니다. {leader}{followers}. 이 카테고리 순위는 결정적 카테고리 할당, 역대 순위 데이터, 저장소 필드에서 생성됩니다.",
  categoryDetailQ: "{label}에는 어떤 저장소가 포함되나요?",
  categoryDetailAWithAsOf:
    "{asOf} 기준으로 {label}에는 GitStarClub ≥10k 화이트리스트의 저장소 {count}개가 포함됩니다. 결정적 규칙 슬라이스이며 GitHub 전체 목록이 아닙니다.",
  categoryDetailANoAsOf:
    "{label}에는 로드된 카테고리 레지스트리에 따라 ≥10k 화이트리스트의 저장소 {count}개가 포함됩니다. 규칙 슬라이스이며 GitHub 전체 목록이 아닙니다.",
  categoryDetailLeaderQ: "{label}을 이끄는 저장소는 무엇인가요?",
  categoryDetailLeaderA: "{repo}가 {value}로 {label}을 이끌고 있습니다.",
  categoryDetailLeaderFallbackA: "{label} 순위는 카테고리 순위 행을 기다리고 있습니다.",
  categoryDetailRunnerQ: "{label}에서 {repo} 다음은 무엇인가요?",
  categoryDetailRunnerFallbackQ: "{label}은 후속 저장소를 표시하나요?",
  categoryDetailRunnerA: "{repo}가 {label}에서 뒤따르며 {value}입니다.",
  categoryDetailRunnerFallbackA: "카테고리 순위 행이 있으면 후속 저장소가 표시됩니다.",
  categoryDetailDataQ: "{label} 순위는 어떻게 생성되나요?",
  categoryDetailDataA:
    "GitStarClub은 ≥10k 화이트리스트 위에서 결정적 카테고리 할당, 역대 순위 데이터, 저장소 필드를 결합합니다. GitHub의 완전한 언어·주제 목록이 아니며 실시간 검색이나 AI도 호출하지 않습니다.",
  totalStarsValue: "{value} 총 스타",
  gainedStarsValue: "{value} 스타",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "주간 상승 목록은 순위 행을 기다리고 있습니다",
  pulseMonthFallback: "월간 상승 목록은 활동 데이터를 기다리고 있습니다",
  pulseWeekLead: "{repo}가 {period}에서 {value} 스타 증가로 앞서고 있습니다",
  pulseMonthLead: "{repo}가 {period}에서 {value} 스타 증가로 앞서고 있습니다",
  pulseCapsule:
    "{asOf} 기준으로 GitStarClub Pulse는 추적 저장소의 현재 오픈소스 움직임을 요약합니다. {weekLead}; {monthLead}. 이 페이지는 GitStarClub의 사전 계산 활동 및 순위 데이터에서 생성되며 런타임 검색, 데이터베이스, AI를 사용하지 않습니다.",
  pulseShowQ: "GitStarClub Pulse는 무엇을 보여주나요?",
  pulseShowAWithAsOf: "{asOf} 기준으로 GitStarClub Pulse는 추적 저장소의 현재 오픈소스 움직임을 요약합니다.",
  pulseShowANoAsOf: "GitStarClub Pulse는 GitStarClub의 사전 계산 활동 및 순위 데이터에서 현재 오픈소스 움직임을 요약합니다.",
  pulseWeekQ: "사용 가능한 최신 주 {period}를 이끄는 저장소는 무엇인가요?",
  pulseWeekA: "{repo}가 {period}에서 {value} 스타 증가로 앞서고 있습니다.",
  pulseWeekFallbackA: "{period} 주간 상승 목록은 순위 행을 기다리고 있습니다.",
  pulseMonthQ: "현재 월간 보기 {period}를 이끄는 저장소는 무엇인가요?",
  pulseMonthA: "{repo}가 {period}에서 {value} 스타 증가로 앞서고 있습니다.",
  pulseMonthFallbackA: "{period} 월간 상승 목록은 활동 데이터를 기다리고 있습니다.",
  pulseDataQ: "Pulse는 어떤 데이터로 만들어지나요?",
  pulseDataA: "Pulse는 GitStarClub의 사전 계산 활동, 주간 순위, 역대 순위, 저장소 데이터를 사용합니다.",
  rankingsRepoFallback: "저장소 목록은 행을 기다리고 있습니다",
  rankingsOrgFallback: "조직 목록은 행을 기다리고 있습니다",
  rankingsRepoLead: "저장소에서는 {repo}가 {value} 총 스타로 앞서고 있습니다",
  rankingsOrgLead: "조직에서는 {org}가 {repos}개 추적 저장소에서 {value} 총 스타로 앞서고 있습니다",
  rankingsCapsule:
    "{asOf} 기준으로 GitStarClub의 역대 순위는 가장 큰 추적 GitHub 저장소와 조직을 요약합니다. {repoLead}; 한편 {orgLead}. 이 페이지는 GitStarClub의 사전 계산 역대 순위, 저장소, 조직 데이터로 만들어집니다.",
  rankingsShowQ: "역대 GitHub 스타 순위는 무엇을 보여주나요?",
  rankingsShowAWithAsOf: "{asOf} 기준으로 역대 순위는 현재 총 스타 수 기준 가장 큰 추적 GitHub 저장소와 조직을 보여줍니다.",
  rankingsShowANoAsOf: "역대 순위는 GitStarClub의 사전 계산 순위 데이터에서 현재 총 스타 수 기준 가장 큰 추적 GitHub 저장소와 조직을 보여줍니다.",
  rankingsRepoQ: "역대 순위를 이끄는 저장소는 무엇인가요?",
  rankingsRepoA: "{repo}가 {value} 총 스타로 표시된 저장소 순위를 이끌고 있습니다.",
  rankingsRepoFallbackA: "표시된 저장소 순위는 사전 계산된 순위 행을 기다리고 있습니다.",
  rankingsOrgQ: "역대 순위를 이끄는 조직은 무엇인가요?",
  rankingsOrgA: "{org}가 {repos}개 추적 저장소에서 {value} 총 스타로 표시된 조직 순위를 이끌고 있습니다.",
  rankingsOrgFallbackA: "표시된 조직 순위는 사전 계산된 조직 순위 행을 기다리고 있습니다.",
  rankingsDataQ: "역대 순위 FAQ는 어떤 데이터로 만들어지나요?",
  rankingsDataA: "GitStarClub은 사전 계산 역대 순위, 저장소, 조직 데이터로 이 FAQ를 만듭니다.",
  compareCapsule:
    "{asOf} 기준으로 GitStarClub Compare는 GitStarClub의 사전 계산 스타 히스토리 데이터에서 추적 저장소의 스타 히스토리 곡선을 겹쳐 보여줍니다. 정적 페이지는 절대 달력 히스토리와 1만 스타 정렬 비교를 설명하며, 클라이언트 전용 쿼리 상태를 서버 렌더링 근거로 주장하지 않습니다.",
  compareWhatQ: "GitStarClub Compare는 무엇을 하나요?",
  compareWhatAWithAsOf: "{asOf} 기준으로 GitStarClub Compare는 GitStarClub의 사전 계산 스타 히스토리 데이터에서 추적 저장소의 스타 히스토리 곡선을 겹쳐 보여줍니다.",
  compareWhatANoAsOf: "GitStarClub Compare는 GitStarClub의 사전 계산 스타 히스토리 데이터에서 추적 저장소의 스타 히스토리 곡선을 겹쳐 보여줍니다.",
  compareReposQ: "어떤 저장소를 비교할 수 있나요?",
  compareReposA: "Compare는 react/react, vuejs/vue 같은 저장소 full name을 사용해 GitStarClub이 이미 추적하는 저장소를 받습니다.",
  compareModesQ: "어떤 비교 모드가 있나요?",
  compareModesA: "독자는 절대 달력 히스토리를 비교하거나, 마일스톤이 있을 때 1만 스타 도달 시점부터 정렬할 수 있습니다.",
  compareQueryQ: "compare FAQ는 URL 쿼리 상태를 설명하나요?",
  compareQueryA: "아니요. 정적 compare 페이지는 결정적인 비교 도구를 설명하며 클라이언트 전용 선택을 서버 렌더링 증거로 주장하지 않습니다.",
};
