import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "完整排名",
  browseAllRepositories: "瀏覽全部 {count} 個倉庫",
  page: "頁",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "{year} GitHub 星標排名 - 年度成長",
  yearMetaDescription: "{year} 年依新增星標排序的 GitHub 倉庫排名，並包含逐月歷史。",
  periodMetaTitle: "{label} GitHub 星標排名",
  periodMetaDescription: "依 {label} 期間新增星標排序的 GitHub 倉庫。",
  categoryIndexMetaTitle: "GitHub 倉庫分類",
  categoryIndexMetaDescription: "依語言、生態、領域、專案類型、擁有者類型和成熟度瀏覽已追蹤 GitHub 倉庫。",
  categoryDimensionMetaTitle: "{label} 分類",
  categoryDimensionMetaDescription: "依 {label} 瀏覽已追蹤 GitHub 倉庫。",
  categoryDetailMetaTitle: "{label} GitHub 倉庫排名{pageSuffix}",
  categoryDetailMetaDescription: "{label} 分類中的已追蹤 GitHub 倉庫，依目前星標排序{pageSuffix}。",
  pageSuffix: " - 第 {page} 頁",
  repositoryRankingsCaption: "{label} GitHub 倉庫排名",
  completeRepositoryRankingsCaption: "{label} GitHub 倉庫完整排名",
  gainedCaption: "{label} GitHub 倉庫依新增星標排序",
  growthCaption: "{label} GitHub 倉庫依成長率排序",
  crossedCaption: "{label} 突破 1 萬星的 GitHub 倉庫",
  categorySummaryCaption: "公開 GitHub 倉庫分類",
  categoryDimensionSummaryCaption: "{label} GitHub 倉庫分類",
  categoryDetailCaption: "{label} 倉庫依目前星標排序",
  categoryPagination: "{label} 分頁",
  range: "{total} 個中的 {first}-{last}",
  rankingDatasetName: "GitStarClub {label} 排名資料集",
  rankingDatasetDescription: "{label} GitHub 倉庫排名，由可用的 GitStarClub 預先計算排名資料產生。",
  rankingCollectionName: "{label} GitHub 倉庫排名",
  rankingItemListName: "{label} GitHub 倉庫排名",
  rankingMetricGained: "所選期間新增星標",
  rankingMetricTotal: "目前總星標",
  rankingLeader: "{repo} 以 {value} 領先",
  rankingFollowers: "，隨後是 {second} 和 {third}",
  rankingEmpty: "可見列表正在等待排名列",
  rankingCapsule:
    "截至 {asOf}，{title} 依{metric}為已追蹤 GitHub 倉庫排名。{leader}{followers}。GitStarClub 從預先計算排名和倉庫資料產生此可見排名，不使用執行時搜尋、資料庫或 AI。",
  rankingWhatQ: "{title} 排名的是什麼？",
  rankingWhatAWithAsOf: "截至 {asOf}，{title} 依{metric}為已追蹤 GitHub 倉庫排名。",
  rankingWhatANoAsOf: "{title} 從 GitStarClub 預先計算排名資料中依{metric}為已追蹤 GitHub 倉庫排名。",
  rankingLeaderQ: "{title} 的領先倉庫是哪個？",
  rankingLeaderA: "{repo} 以 {value} 領先 {title}。",
  rankingLeaderFallbackA: "{title} 的可見列表正在等待排名列。",
  rankingRunnerQ: "{title} 中誰跟隨 {repo}？",
  rankingRunnerFallbackQ: "{title} 是否包含後續倉庫？",
  rankingRunnerA: "{repo} 以 {value} 出現在可見排名下一位。",
  rankingRunnerFallbackA: "當預先計算排名至少有兩個倉庫時，會顯示後續列。",
  rankingDataQ: "{title} 使用即時資料庫查詢嗎？",
  rankingDataA: "不使用。GitStarClub 從預先計算排名和倉庫資料渲染 {title}。",
  categoryIndexDatasetName: "GitStarClub 分類註冊表資料集",
  categoryIndexDatasetDescription: "按語言、生態系、領域、專案類型、擁有者類型、成熟度等瀏覽公開 GitHub 倉庫分類。",
  categoryIndexCollectionName: "GitHub 倉庫分類",
  categoryIndexItemListName: "GitHub 倉庫分類",
  categoryIndexCapsule:
    "截至 {asOf}，GitStarClub 將已追蹤 GitHub 倉庫整理為 {dimensions} 個維度下的 {categories} 個公開分類，包括 {labels}。分類連結由基於倉庫中繼資料的確定性規則產生，而不是即時搜尋或 AI。",
  categoryIndexQ: "GitStarClub 上的 GitHub 倉庫分類是什麼？",
  categoryIndexAWithAsOf: "截至 {asOf}，GitStarClub 將已追蹤倉庫整理為 {dimensions} 個維度下的 {categories} 個公開分類。",
  categoryIndexANoAsOf: "GitStarClub 將已追蹤倉庫整理為 {dimensions} 個維度下的 {categories} 個公開分類。",
  categoryDimensionsQ: "有哪些分類維度？",
  categoryDimensionsA: "可見分類維度是 {labels}。",
  categoryCountsQ: "分類計數來自哪裡？",
  categoryCountsA: "分類計數來自 GitStarClub 自有分類資料：基於倉庫中繼資料的確定性規則，而不是即時搜尋或 AI。",
  categoryMoveQ: "讀者如何從分類進入倉庫？",
  categoryMoveAWithDimension: "讀者可以開啟 {label} 等維度，再跟隨分類連結進入已排名倉庫列表。",
  categoryMoveAFallback: "讀者可以開啟任意可見維度，再跟隨分類連結進入已排名倉庫列表。",
  categoryDimensionDatasetName: "GitStarClub {label} 分類資料集",
  categoryDimensionDatasetDescription: "瀏覽 {label} 分類定義、計數和面向已追蹤 GitHub 倉庫的可抓取連結。",
  categoryDimensionCollectionName: "{label} 分類",
  categoryDimensionItemListName: "{label} 分類",
  categoryDimensionCapsule:
    "截至 {asOf}，GitStarClub 為已追蹤 GitHub 倉庫列出 {label} 維度下的 {categories} 個公開分類。此頁面使用基於倉庫中繼資料的確定性規則，而不是即時搜尋或 AI，並用可抓取連結幫助讀者從分類進入具體倉庫排名。",
  categoryDimensionQ: "{label} 分類頁包含什麼？",
  categoryDimensionAWithAsOf: "截至 {asOf}，{label} 頁面列出已追蹤 GitHub 倉庫的 {categories} 個公開分類。",
  categoryDimensionANoAsOf: "{label} 頁面列出已追蹤 GitHub 倉庫的 {categories} 個公開分類。",
  categoryLargestQ: "哪個 {label} 分類的追蹤倉庫最多？",
  categoryLargestA: "{category} 是可見 {label} 分類中最大的，有 {count} 個追蹤倉庫。",
  categoryLargestFallbackA: "暫無公開 {label} 分類計數。",
  categoryLinksQ: "{label} 分類連結如何產生？",
  categoryLinksA: "GitStarClub 使用請求前已預先計算的 public 標記、slug、label 和 count，從分類註冊表渲染 {label} 連結。",
  categoryNoClientQ: "{label} 頁面會執行客戶端篩選嗎？",
  categoryNoClientA: "不會。{label} 頁面由伺服器渲染，不為可見 FAQ 或分類連結加入客戶端篩選邏輯。",
  categoryDetailDatasetName: "GitStarClub {label} 倉庫資料集",
  categoryDetailDatasetDescription: "{label} 倉庫排名由確定性分類分配、歷史總榜資料和倉庫欄位產生。",
  categoryDetailCollectionName: "{label} 倉庫",
  categoryDetailItemListName: "{label} 倉庫",
  categoryDetailCapsule:
    "截至 {asOf}，GitStarClub 在 {label} 中追蹤 {count} 個倉庫。{leader}{followers}。此分類排名由確定性分類分配、歷史總榜資料和倉庫欄位產生。",
  categoryDetailQ: "{label} 中包含哪些倉庫？",
  categoryDetailAWithAsOf: "截至 {asOf}，{label} 包含 GitStarClub ≥10k 白名單中的 {count} 個倉庫——這是確定性規則切片，不是完整的 GitHub 目錄。",
  categoryDetailANoAsOf: "根據已載入的分類註冊表，{label} 包含 ≥10k 白名單中的 {count} 個倉庫——這是規則切片，不是完整的 GitHub 目錄。",
  categoryDetailLeaderQ: "{label} 的領先倉庫是哪個？",
  categoryDetailLeaderA: "{repo} 以 {value} 領先 {label}。",
  categoryDetailLeaderFallbackA: "{label} 排名正在等待分類排名列。",
  categoryDetailRunnerQ: "{label} 中誰跟隨 {repo}？",
  categoryDetailRunnerFallbackQ: "{label} 是否顯示後續倉庫？",
  categoryDetailRunnerA: "{repo} 在 {label} 中隨後，目前為 {value}。",
  categoryDetailRunnerFallbackA: "分類排名列可用時會顯示後續倉庫。",
  categoryDetailDataQ: "{label} 排名如何產生？",
  categoryDetailDataA: "GitStarClub 在 ≥10k 白名單上組合確定性分類分配、歷史總榜資料和倉庫欄位。這不是完整的 GitHub 語言或主題列表，也不會呼叫即時搜尋或 AI。",
  totalStarsValue: "{value} 總星標",
  gainedStarsValue: "{value} 星",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "週度上升列表正在等待排名列",
  pulseMonthFallback: "月度上升列表正在等待活動資料",
  pulseWeekLead: "{repo} 以新增 {value} 星領先 {period}",
  pulseMonthLead: "{repo} 以新增 {value} 星領先 {period}",
  pulseCapsule:
    "截至 {asOf}，GitStarClub Pulse 彙總追蹤倉庫中的目前開源動量。{weekLead}；{monthLead}。該頁面由 GitStarClub 預先計算活動和排名資料產生，不依賴執行時搜尋、資料庫或 AI。",
  pulseShowQ: "GitStarClub Pulse 展示什麼？",
  pulseShowAWithAsOf: "截至 {asOf}，GitStarClub Pulse 彙總追蹤倉庫中的目前開源動量。",
  pulseShowANoAsOf: "GitStarClub Pulse 從 GitStarClub 預先計算活動和排名資料彙總目前開源動量。",
  pulseWeekQ: "最新可用週 {period} 由哪個倉庫領先？",
  pulseWeekA: "{repo} 以新增 {value} 星領先 {period}。",
  pulseWeekFallbackA: "{period} 的週度上升列表正在等待排名列。",
  pulseMonthQ: "目前月度視圖 {period} 由哪個倉庫領先？",
  pulseMonthA: "{repo} 以新增 {value} 星領先 {period}。",
  pulseMonthFallbackA: "{period} 的月度上升列表正在等待活動資料。",
  pulseDataQ: "Pulse 由哪些資料驅動？",
  pulseDataA: "Pulse 使用 GitStarClub 預先計算活動、週度排名、歷史總榜和倉庫資料。",
  rankingsRepoFallback: "倉庫列表正在等待列資料",
  rankingsOrgFallback: "組織列表正在等待列資料",
  rankingsRepoLead: "倉庫中 {repo} 以 {value} 總星標領先",
  rankingsOrgLead: "組織中 {org} 在 {repos} 個追蹤倉庫中以 {value} 總星標領先",
  rankingsCapsule:
    "截至 {asOf}，GitStarClub 歷史總榜彙總最大的已追蹤 GitHub 倉庫與組織。{repoLead}；同時，{orgLead}。該頁面由 GitStarClub 預先計算歷史總榜、倉庫和組織資料產生。",
  rankingsShowQ: "GitHub 歷史總星標排行榜展示什麼？",
  rankingsShowAWithAsOf: "截至 {asOf}，歷史總榜依目前總星標列出最大的已追蹤 GitHub 倉庫與組織。",
  rankingsShowANoAsOf: "歷史總榜從 GitStarClub 預先計算排名資料中依目前總星標列出最大的已追蹤 GitHub 倉庫與組織。",
  rankingsRepoQ: "哪個倉庫領先歷史總榜？",
  rankingsRepoA: "{repo} 以 {value} 總星標領先可見倉庫榜。",
  rankingsRepoFallbackA: "可見倉庫榜正在等待預先計算排名列。",
  rankingsOrgQ: "哪個組織領先歷史總榜？",
  rankingsOrgA: "{org} 在 {repos} 個追蹤倉庫中以 {value} 總星標領先可見組織榜。",
  rankingsOrgFallbackA: "可見組織榜正在等待預先計算組織排名列。",
  rankingsDataQ: "歷史總榜 FAQ 由哪些資料驅動？",
  rankingsDataA: "GitStarClub 從預先計算歷史總榜、倉庫和組織資料建立此 FAQ。",
  compareCapsule:
    "截至 {asOf}，GitStarClub Compare 可從 GitStarClub 預先計算星標歷史資料疊加追蹤倉庫的星標歷史曲線。靜態頁面說明絕對日曆歷史和 1 萬星對齊比較，不把僅客戶端的查詢狀態當作伺服器渲染證據。",
  compareWhatQ: "GitStarClub Compare 做什麼？",
  compareWhatAWithAsOf: "截至 {asOf}，GitStarClub Compare 可從 GitStarClub 預先計算星標歷史資料疊加追蹤倉庫的星標歷史曲線。",
  compareWhatANoAsOf: "GitStarClub Compare 可從 GitStarClub 預先計算星標歷史資料疊加追蹤倉庫的星標歷史曲線。",
  compareReposQ: "哪些倉庫可以對比？",
  compareReposA: "Compare 接受 GitStarClub 已追蹤的倉庫，使用 react/react 和 vuejs/vue 這樣的倉庫 full name。",
  compareModesQ: "有哪些對比模式？",
  compareModesA: "讀者可以比較絕對日曆歷史，也可以在里程碑可用時從 1 萬星節點對齊比較。",
  compareQueryQ: "compare FAQ 會描述 URL 查詢狀態嗎？",
  compareQueryA: "不會。靜態 compare 頁面解釋決定性的比較工具，不把僅客戶端選擇當作伺服器渲染證據。",
};
