import type { CoreSeoCopy, DetailText } from "./types";

export const detail: DetailText = {
  completeRanking: "完整排名",
  browseAllRepositories: "浏览全部 {count} 个仓库",
  page: "页",
  sourceSuffix: " - GitStarClub",
  yearMetaTitle: "{year} GitHub 星标排名 - 年度增长",
  yearMetaDescription: "{year} 年按新增星标排序的 GitHub 仓库排名，并包含逐月历史。",
  periodMetaTitle: "{label} GitHub 星标排名",
  periodMetaDescription: "按 {label} 期间新增星标排序的 GitHub 仓库。",
  categoryIndexMetaTitle: "GitHub 仓库分类",
  categoryIndexMetaDescription: "按语言、生态、领域、项目类型、所有者类型和成熟度浏览已追踪 GitHub 仓库。",
  categoryDimensionMetaTitle: "{label} 分类",
  categoryDimensionMetaDescription: "按 {label} 浏览已追踪 GitHub 仓库。",
  categoryDetailMetaTitle: "{label} GitHub 仓库排名{pageSuffix}",
  categoryDetailMetaDescription: "{label} 分类中的已追踪 GitHub 仓库，按当前星标排序{pageSuffix}。",
  pageSuffix: " - 第 {page} 页",
  repositoryRankingsCaption: "{label} GitHub 仓库排名",
  completeRepositoryRankingsCaption: "{label} GitHub 仓库完整排名",
  gainedCaption: "{label} GitHub 仓库按新增星标排序",
  growthCaption: "{label} GitHub 仓库按增长率排序",
  crossedCaption: "{label} 突破 1 万星的 GitHub 仓库",
  categorySummaryCaption: "公开 GitHub 仓库分类",
  categoryDimensionSummaryCaption: "{label} GitHub 仓库分类",
  categoryDetailCaption: "{label} 仓库按当前星标排序",
  categoryPagination: "{label} 分页",
  range: "{total} 个中的 {first}-{last}",
  rankingDatasetName: "GitStarClub {label} 排名数据集",
  rankingDatasetDescription: "{label} GitHub 仓库排名，由可用的 GitStarClub 预计算排名数据生成。",
  rankingCollectionName: "{label} GitHub 仓库排名",
  rankingItemListName: "{label} GitHub 仓库排名",
  rankingMetricGained: "所选期间新增星标",
  rankingMetricTotal: "当前总星标",
  rankingLeader: "{repo} 以 {value} 领先",
  rankingFollowers: "，随后是 {second} 和 {third}",
  rankingEmpty: "可见列表正在等待排名行",
  rankingCapsule:
    "截至 {asOf}，{title} 按{metric}为已追踪 GitHub 仓库排名。{leader}{followers}。GitStarClub 从预计算排名和仓库数据生成此可见排名，不使用运行时搜索、数据库或 AI。",
  rankingWhatQ: "{title} 排名的是什么？",
  rankingWhatAWithAsOf: "截至 {asOf}，{title} 按{metric}为已追踪 GitHub 仓库排名。",
  rankingWhatANoAsOf: "{title} 从 GitStarClub 预计算排名数据中按{metric}为已追踪 GitHub 仓库排名。",
  rankingLeaderQ: "{title} 的领先仓库是哪个？",
  rankingLeaderA: "{repo} 以 {value} 领先 {title}。",
  rankingLeaderFallbackA: "{title} 的可见列表正在等待排名行。",
  rankingRunnerQ: "{title} 中谁跟随 {repo}？",
  rankingRunnerFallbackQ: "{title} 是否包含后续仓库？",
  rankingRunnerA: "{repo} 以 {value} 出现在可见排名下一位。",
  rankingRunnerFallbackA: "当预计算排名至少有两个仓库时，会显示后续行。",
  rankingDataQ: "{title} 使用实时数据库查询吗？",
  rankingDataA: "不使用。GitStarClub 从预计算排名和仓库数据渲染 {title}。",
  categoryIndexDatasetName: "GitStarClub 分类注册表数据集",
  categoryIndexDatasetDescription: "按语言、生态、领域、项目类型、所有者类型、成熟度等浏览公开 GitHub 仓库分类。",
  categoryIndexCollectionName: "GitHub 仓库分类",
  categoryIndexItemListName: "GitHub 仓库分类",
  categoryIndexCapsule:
    "截至 {asOf}，GitStarClub 将已追踪 GitHub 仓库整理为 {dimensions} 个维度下的 {categories} 个公开分类，包括 {labels}。分类链接由基于仓库元数据的确定性规则生成，而不是实时搜索或 AI。",
  categoryIndexQ: "GitStarClub 上的 GitHub 仓库分类是什么？",
  categoryIndexAWithAsOf: "截至 {asOf}，GitStarClub 将已追踪仓库整理为 {dimensions} 个维度下的 {categories} 个公开分类。",
  categoryIndexANoAsOf: "GitStarClub 将已追踪仓库整理为 {dimensions} 个维度下的 {categories} 个公开分类。",
  categoryDimensionsQ: "有哪些分类维度？",
  categoryDimensionsA: "可见分类维度是 {labels}。",
  categoryCountsQ: "分类计数来自哪里？",
  categoryCountsA: "分类计数来自 GitStarClub 自有分类数据：基于仓库元数据的确定性规则，而不是实时搜索或 AI。",
  categoryMoveQ: "读者如何从分类进入仓库？",
  categoryMoveAWithDimension: "读者可以打开 {label} 等维度，再跟随分类链接进入已排名仓库列表。",
  categoryMoveAFallback: "读者可以打开任意可见维度，再跟随分类链接进入已排名仓库列表。",
  categoryDimensionDatasetName: "GitStarClub {label} 分类数据集",
  categoryDimensionDatasetDescription: "浏览 {label} 分类定义、计数和面向已追踪 GitHub 仓库的可抓取链接。",
  categoryDimensionCollectionName: "{label} 分类",
  categoryDimensionItemListName: "{label} 分类",
  categoryDimensionCapsule:
    "截至 {asOf}，GitStarClub 为已追踪 GitHub 仓库列出 {label} 维度下的 {categories} 个公开分类。该页面使用基于仓库元数据的确定性规则，而不是实时搜索或 AI，并用可抓取链接帮助读者从分类进入具体仓库排名。",
  categoryDimensionQ: "{label} 分类页包含什么？",
  categoryDimensionAWithAsOf: "截至 {asOf}，{label} 页面列出已追踪 GitHub 仓库的 {categories} 个公开分类。",
  categoryDimensionANoAsOf: "{label} 页面列出已追踪 GitHub 仓库的 {categories} 个公开分类。",
  categoryLargestQ: "哪个 {label} 分类的追踪仓库最多？",
  categoryLargestA: "{category} 是可见 {label} 分类中最大的一个，有 {count} 个追踪仓库。",
  categoryLargestFallbackA: "暂无公开 {label} 分类计数。",
  categoryLinksQ: "{label} 分类链接如何生成？",
  categoryLinksA: "GitStarClub 使用请求前已预计算的 public 标记、slug、label 和 count，从分类注册表渲染 {label} 链接。",
  categoryNoClientQ: "{label} 页面会运行客户端过滤吗？",
  categoryNoClientA: "不会。{label} 页面由服务器渲染，不为可见 FAQ 或分类链接添加客户端过滤逻辑。",
  categoryDetailDatasetName: "GitStarClub {label} 仓库数据集",
  categoryDetailDatasetDescription: "{label} 仓库排名由确定性分类分配、历史总榜数据和仓库字段生成。",
  categoryDetailCollectionName: "{label} 仓库",
  categoryDetailItemListName: "{label} 仓库",
  categoryDetailCapsule:
    "截至 {asOf}，GitStarClub 在 {label} 中追踪 {count} 个仓库。{leader}{followers}。该分类排名由确定性分类分配、历史总榜数据和仓库字段生成。",
  categoryDetailQ: "{label} 中包含哪些仓库？",
  categoryDetailAWithAsOf: "截至 {asOf}，{label} 包含 GitStarClub ≥10k 白名单中的 {count} 个仓库——这是确定性规则切片，不是完整的 GitHub 目录。",
  categoryDetailANoAsOf: "根据已加载的分类注册表，{label} 包含 ≥10k 白名单中的 {count} 个仓库——这是规则切片，不是完整的 GitHub 目录。",
  categoryDetailLeaderQ: "{label} 的领先仓库是哪个？",
  categoryDetailLeaderA: "{repo} 以 {value} 领先 {label}。",
  categoryDetailLeaderFallbackA: "{label} 排名正在等待分类排名行。",
  categoryDetailRunnerQ: "{label} 中谁跟随 {repo}？",
  categoryDetailRunnerFallbackQ: "{label} 是否显示后续仓库？",
  categoryDetailRunnerA: "{repo} 在 {label} 中随后，当前为 {value}。",
  categoryDetailRunnerFallbackA: "分类排名行可用时会显示后续仓库。",
  categoryDetailDataQ: "{label} 排名如何生成？",
  categoryDetailDataA: "GitStarClub 在 ≥10k 白名单上组合确定性分类分配、历史总榜数据和仓库字段。这不是完整的 GitHub 语言或主题列表，也不会调用实时搜索或 AI。",
  totalStarsValue: "{value} 总星标",
  gainedStarsValue: "{value} 星",
};

export const seo: CoreSeoCopy = {
  sourceSuffix: " - GitStarClub",
  pulseWeekFallback: "周度上涨列表正在等待排名行",
  pulseMonthFallback: "月度上涨列表正在等待活动数据",
  pulseWeekLead: "{repo} 以新增 {value} 星领先 {period}",
  pulseMonthLead: "{repo} 以新增 {value} 星领先 {period}",
  pulseCapsule:
    "截至 {asOf}，GitStarClub Pulse 汇总追踪仓库中的当前开源动量。{weekLead}；{monthLead}。该页面由 GitStarClub 预计算活动和排名数据生成，不依赖运行时搜索、数据库或 AI。",
  pulseShowQ: "GitStarClub Pulse 展示什么？",
  pulseShowAWithAsOf: "截至 {asOf}，GitStarClub Pulse 汇总追踪仓库中的当前开源动量。",
  pulseShowANoAsOf: "GitStarClub Pulse 从 GitStarClub 预计算活动和排名数据汇总当前开源动量。",
  pulseWeekQ: "最新可用周 {period} 由哪个仓库领先？",
  pulseWeekA: "{repo} 以新增 {value} 星领先 {period}。",
  pulseWeekFallbackA: "{period} 的周度上涨列表正在等待排名行。",
  pulseMonthQ: "当前月度视图 {period} 由哪个仓库领先？",
  pulseMonthA: "{repo} 以新增 {value} 星领先 {period}。",
  pulseMonthFallbackA: "{period} 的月度上涨列表正在等待活动数据。",
  pulseDataQ: "Pulse 由哪些数据驱动？",
  pulseDataA: "Pulse 使用 GitStarClub 预计算活动、周度排名、历史总榜和仓库数据。",
  rankingsRepoFallback: "仓库列表正在等待行数据",
  rankingsOrgFallback: "组织列表正在等待行数据",
  rankingsRepoLead: "仓库中 {repo} 以 {value} 总星标领先",
  rankingsOrgLead: "组织中 {org} 在 {repos} 个追踪仓库中以 {value} 总星标领先",
  rankingsCapsule:
    "截至 {asOf}，GitStarClub 历史总榜汇总最大的已追踪 GitHub 仓库与组织。{repoLead}；同时，{orgLead}。该页面由 GitStarClub 预计算历史总榜、仓库和组织数据生成。",
  rankingsShowQ: "GitHub 历史总星标排行榜展示什么？",
  rankingsShowAWithAsOf: "截至 {asOf}，历史总榜按当前总星标列出最大的已追踪 GitHub 仓库与组织。",
  rankingsShowANoAsOf: "历史总榜从 GitStarClub 预计算排名数据中按当前总星标列出最大的已追踪 GitHub 仓库与组织。",
  rankingsRepoQ: "哪个仓库领先历史总榜？",
  rankingsRepoA: "{repo} 以 {value} 总星标领先可见仓库榜。",
  rankingsRepoFallbackA: "可见仓库榜正在等待预计算排名行。",
  rankingsOrgQ: "哪个组织领先历史总榜？",
  rankingsOrgA: "{org} 在 {repos} 个追踪仓库中以 {value} 总星标领先可见组织榜。",
  rankingsOrgFallbackA: "可见组织榜正在等待预计算组织排名行。",
  rankingsDataQ: "历史总榜 FAQ 由哪些数据驱动？",
  rankingsDataA: "GitStarClub 从预计算历史总榜、仓库和组织数据构建此 FAQ。",
  compareCapsule:
    "截至 {asOf}，GitStarClub Compare 可从 GitStarClub 预计算星标历史数据叠加追踪仓库的星标历史曲线。静态页面说明绝对日历历史和 1 万星对齐比较，不把仅客户端的查询状态当作服务器渲染证据。",
  compareWhatQ: "GitStarClub Compare 做什么？",
  compareWhatAWithAsOf: "截至 {asOf}，GitStarClub Compare 可从 GitStarClub 预计算星标历史数据叠加追踪仓库的星标历史曲线。",
  compareWhatANoAsOf: "GitStarClub Compare 可从 GitStarClub 预计算星标历史数据叠加追踪仓库的星标历史曲线。",
  compareReposQ: "哪些仓库可以对比？",
  compareReposA: "Compare 接受 GitStarClub 已追踪的仓库，使用 react/react 和 vuejs/vue 这样的仓库 full name。",
  compareModesQ: "有哪些对比模式？",
  compareModesA: "读者可以比较绝对日历历史，也可以在里程碑可用时从 1 万星节点对齐比较。",
  compareQueryQ: "compare FAQ 会描述 URL 查询状态吗？",
  compareQueryA: "不会。静态 compare 页面解释确定性的比较工具，不把仅客户端选择当作服务器渲染证据。",
};
