import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "../..");

function git(root: string, ...args: string[]): string | null {
  const result = spawnSync("git", args, { cwd: root, encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : null;
}

export function resolveCfBuildCommitSha(
  override: string | undefined,
  head: string | null,
  status: string | null,
): string | null {
  const sha = override?.trim() || head;
  if (!sha || !/^[a-f0-9]{40,64}$/i.test(sha) || status === null) return null;
  return status ? `${sha}-dirty` : sha;
}

export function writeCfBuildIdentity(override = process.env.CF_BUILD_COMMIT_SHA, root = repoRoot): string | null {
  const head = git(root, "rev-parse", "HEAD");
  // Read status before writing. The generated module is gitignored.
  // Untracked files are ignored so local notes do not mark the SHA dirty.
  const status = git(root, "status", "--porcelain", "--untracked-files=no", "--", ".");
  const sha = resolveCfBuildCommitSha(override, head, status);
  writeFileSync(join(root, "web/lib/cf-build-identity.ts"), `// Generated by cf:build; do not commit.\nexport const cfBuildCommitSha: string | null = ${JSON.stringify(sha)};\n`);
  return sha;
}

if (import.meta.main) console.log(`CF build identity: ${writeCfBuildIdentity() ?? "null"}`);
